### ISSUE TITLE
Crashes after newest 0.14.156 Update

### ISSUE THREAD

**Issue by vlachmilan** [Haehnchen/idea-php-symfony2-plugin#1050]
Hey guys,

I just updated to the newest Symfony plugin right now, but PHPSTORM is now crashing until I disable it. 
Reinstalling doesn't help, nor good old on/off solution. 

The crashes appear to occur while I just start the plugin. Different versions of symfony doesn't appear to have any differences, neither does switching projects. 
 
**PHPSTORM informations:** 
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-72-generic

I think I cannot provide you any more details than the output:
```
om/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.resolve(ContainerCollectionResolver.java:147)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getResolvedClassDefinition(ServiceUtil.java:158)
	at fr.adrienbrault.idea.symfony2plugin.dic.container.util.ServiceContainerUtil.getYamlConstructorTypeHint(ServiceContainerUtil.java:321)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getTypeHint(ServiceArgumentParameterHintsProvider.java:79)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getParameterHints(ServiceArgumentParameterHintsProvider.java:49)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:120)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.14.156]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more


java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.resolve(ContainerCollectionResolver.java:147)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getResolvedClassDefinition(ServiceUtil.java:158)
	at fr.adrienbrault.idea.symfony2plugin.dic.container.util.ServiceContainerUtil.getYamlConstructorTypeHint(ServiceContainerUtil.java:321)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getTypeHint(ServiceArgumentParameterHintsProvider.java:79)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getParameterHints(ServiceArgumentParameterHintsProvider.java:49)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:120)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.14.156]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more


```

**Comment by Haehnchen** [comment]
this is because of `2017.1.4` some classes were moved until this version. I think i will open 0.15.x to provide best support for all versions

**Comment by Arkemlar** [comment]
## Yep, unable to use symfony plugin anymore!

![image](https://user-images.githubusercontent.com/19671202/31465772-a0099884-aedd-11e7-9b91-20a53cdbad59.png)
### Phpstprm version info:
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
Licensed to imsxm.com

JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.13.0-24-generic


Please make it work back again.

**Comment by Arkemlar** [comment]
Weird. Just reenabled plugin and it works fine.

**Comment by Haehnchen** [comment]
whats about `0.14.157.1` does that help?

_duplicate of #1057_

**Comment by vlachmilan** [comment]
Yes, now works fine. Thank you!
