### ISSUE TITLE
Worker exited due to exception: com/intellij/util/indexing/IndexId

### ISSUE THREAD

**Issue by nicoorfi** [Haehnchen/idea-php-symfony2-plugin#1057]
`Worker exited due to exception: com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getServices(ContainerCollectionResolver.java:60)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getService(ContainerCollectionResolver.java:55)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getServiceClass(ServiceUtil.java:369)
	at fr.adrienbrault.idea.symfony2plugin.templating.variable.collector.ServiceContainerVariableCollector.collect(ServiceContainerVariableCollector.java:29)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:234)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:216)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.getRootVariableByName(TwigTypeResolveUtil.java:350)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.resolveTwigMethodName(TwigTypeResolveUtil.java:113)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigTemplateGoToLocalDeclarationHandler.getTypeGoto(TwigTemplateGoToLocalDeclarationHandler.java:243)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigTemplateGoToLocalDeclarationHandler.getGotoDeclarationTargets(TwigTemplateGoToLocalDeclarationHandler.java:94)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.14.156]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more

java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getServices(ContainerCollectionResolver.java:60)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getService(ContainerCollectionResolver.java:55)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getServiceClass(ServiceUtil.java:369)
	at fr.adrienbrault.idea.symfony2plugin.templating.variable.collector.ServiceContainerVariableCollector.collect(ServiceContainerVariableCollector.java:29)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:234)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:216)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.getRootVariableByName(TwigTypeResolveUtil.java:350)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.resolveTwigMethodName(TwigTypeResolveUtil.java:113)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigTemplateGoToLocalDeclarationHandler.getTypeGoto(TwigTemplateGoToLocalDeclarationHandler.java:243)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigTemplateGoToLocalDeclarationHandler.getGotoDeclarationTargets(TwigTemplateGoToLocalDeclarationHandler.java:94)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:276)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:153)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.14.156]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
`

Following error since the last update 0.14.156 on Arch linux.

**Comment by b3da-cz** [comment]
I'm getting this too since last update, latest plugin, latest stable phpStorm, ubuntu 16.04.
to reproduce, just composer create new symfony project, open in phpStorm and turn plugin on..

**Comment by thibaultfalque** [comment]
Hi, 
I have the same error but the exception is a little different: 
`
com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getAllRoutesProxy(RouteHelper.java:1005)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.lambda$getAllRoutes$2(RouteHelper.java:988)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getAllRoutes(RouteHelper.java:994)
	at fr.adrienbrault.idea.symfony2plugin.navigation.TwigFoldingBuilder.attachPathFoldingDescriptors(TwigFoldingBuilder.java:98)
	at fr.adrienbrault.idea.symfony2plugin.navigation.TwigFoldingBuilder.buildFoldRegions(TwigFoldingBuilder.java:42)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:63)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:236)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:222)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:112)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:101)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:97)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:326)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:312)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.14.157]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
`
Linux mint 18.1 
PHPSTORM 2017.1.3
Plugin 0.14.157

**Comment by Haehnchen** [comment]
please try `0.14.157.1 ` and consider upgrade to PhpStorm `2016.2` :)

**Comment by Haehnchen** [comment]
done

**Comment by SoboLAN** [comment]
I had the same problem with PHPStorm 2017.1.4 and Symfony2-Plugin 0.14.156.

It was solved by upgrading the plugin to 0.14.157.1.
