### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by bytehead** [Haehnchen/idea-php-symfony2-plugin#1069]
This error just occured, while using PhpStorm after update (no EAP channel).

PhpStorm:
```
2017.2
Build #PS-172.3317.83, built on July 18, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
Symfony-Plugin: `0.15.158`

Stacktrace:
```
null
java.lang.NegativeArraySizeException
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.externalizer.ObjectStreamDataExternalizer.read(ObjectStreamDataExternalizer.java:27)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.externalizer.ObjectStreamDataExternalizer.read(ObjectStreamDataExternalizer.java:11)
	at com.intellij.util.indexing.impl.ValueContainerImpl.readFrom(ValueContainerImpl.java:481)
	at com.intellij.util.indexing.impl.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:87)
	at com.intellij.util.indexing.impl.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:70)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:535)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:484)
	at com.intellij.util.indexing.impl.MapIndexStorage$3$1.compute(MapIndexStorage.java:109)
	at com.intellij.util.indexing.impl.MapIndexStorage$3$1.compute(MapIndexStorage.java:97)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:103)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:82)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:937)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:857)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:936)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:907)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:769)
	at fr.adrienbrault.idea.symfony2plugin.stubs.SymfonyProcessors$CollectProjectUniqueKeys.lambda$getResult$0(SymfonyProcessors.java:46)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.adrienbrault.idea.symfony2plugin.stubs.SymfonyProcessors$CollectProjectUniqueKeys.getResult(SymfonyProcessors.java:47)
	at fr.adrienbrault.idea.symfony2plugin.stubs.SymfonyProcessors.createResult(SymfonyProcessors.java:96)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.lambda$getIndexKeysCache$4(FileIndexCaches.java:95)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.getIndexKeysCache(FileIndexCaches.java:101)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.lambda$getSetDataCache$1(FileIndexCaches.java:42)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.getSetDataCache(FileIndexCaches.java:52)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getServices(ContainerCollectionResolver.java:60)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver.getService(ContainerCollectionResolver.java:55)
	at fr.adrienbrault.idea.symfony2plugin.dic.SymfonyContainerTypeProvider.getBySignature(SymfonyContainerTypeProvider.java:86)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:522)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:366)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:126)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:441)
	at com.jetbrains.php.PhpIndexImpl.completeThis(PhpIndexImpl.java:85)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.globalLocationAware(PhpType.java:419)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:138)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobal(MethodReferenceImpl.java:84)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:145)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:142)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:137)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:123)
	at com.jetbrains.php.ui.PhpParameterHintManager.<init>(PhpParameterHintManager.java:46)
	at com.jetbrains.php.ui.PhpInlayParameterHintsProvider.getParameterHints(PhpInlayParameterHintsProvider.kt:44)
	at com.intellij.codeInsight.hints.ParameterHintsPass.a(ParameterHintsPass.java:109)
	at com.intellij.codeInsight.hints.ParameterHintsPass.a(ParameterHintsPass.java:68)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:68)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by bytehead** [comment]
I've updated PhpStorm to 
``` 
2017.2.4
Build #PS-172.4
155.41, built on September 15, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
and now it works 👍.
