### ISSUE TITLE
Remote Container Setting in PHPStorm

### ISSUE THREAD

**Issue by megadruck** [Haehnchen/idea-php-symfony2-plugin#1104]
Hi

The Container setting in symfony plugin does not work for remote xml files. You can set it, but PhpStorm just look for the local file

![grafik](https://user-images.githubusercontent.com/20039487/33883044-8a890976-df3a-11e7-95f3-9c6cad00c8ec.png)

**Comment by Koc** [comment]
Hm. I am using same functionality and looks like it works properly

**Comment by megadruck** [comment]
As long the file is locally it works. But I set it to remote.

**Comment by Koc** [comment]
Me too

![default](https://user-images.githubusercontent.com/191082/34079254-c36cc33a-e332-11e7-99db-9ab3b4cf1ef7.png)

**Comment by Koc** [comment]
@megadruck maybe you set the wrong path to the file?

@Haehnchen maybe better add to info: `remote, exists` or `remote, not exists`?

**Comment by megadruck** [comment]
The path loooks like ok.
![grafik](https://user-images.githubusercontent.com/20039487/34105906-728353d4-e3f6-11e7-8320-8507423ac245.png)

**Comment by megadruck** [comment]
the xml is not locally. thats how it looks like

![grafik](https://user-images.githubusercontent.com/20039487/34105983-c036a78e-e3f6-11e7-99b6-8d6b3a64de05.png)

if I download it:
![grafik](https://user-images.githubusercontent.com/20039487/34106083-27745d4c-e3f7-11e7-9cf5-d207b539e3d8.png)

**Comment by vctls** [comment]
Does that syntax work with the Translations Root Path on the main settings page, like this?
![image](https://user-images.githubusercontent.com/18054077/34816051-eea1acfc-f6b3-11e7-90db-378cb2ac5d6b.png)

**Comment by kriks57** [comment]
Please consider the case, we are using docker, and the cache directory is "mounted" in a volume (for performance), which is not accessible locally.

**Comment by kriks57** [comment]
In case this could help, if I click the "remote" button in the Symfony/Container section of the settings, nothing happens.

Here is the trace I have : 

`2020-08-05 15:15:17,722 [ 169322]  ERROR - i.remotebrowser.ServerTreeNode - Assertion failed 
java.lang.Throwable: Assertion failed
        at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:179)
        at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:188)
        at com.jetbrains.plugins.webDeployment.ui.remotebrowser.ServerTreeNode.<init>(ServerTreeNode.java:80)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserForm.initialize(ServerBrowserForm.java:78)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserForm.<init>(ServerBrowserForm.java:66)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.createCenterPanel(ServerBrowserDialog.java:71)
        at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1338)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.init(ServerBrowserDialog.java:56)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.<init>(ServerBrowserDialog.java:50)
        at fr.adrienbrault.idea.symfony2plugin.ui.utils.UiSettingsUtil.openFileDialogForDefaultWebServerConnection(UiSettingsUtil.java:66)
        at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm$3.actionPerformed(ContainerSettingsForm.java:146)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
        at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
        at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
        at java.desktop/java.awt.Component.processEvent(Component.java:6415)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:904)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:733)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:710)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:80)
        at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:888)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-08-05 15:15:17,726 [ 169326]  ERROR - i.remotebrowser.ServerTreeNode - PhpStorm 2020.2  Build #PS-202.6397.115 
2020-08-05 15:15:17,726 [ 169326]  ERROR - i.remotebrowser.ServerTreeNode - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-08-05 15:15:17,726 [ 169326]  ERROR - i.remotebrowser.ServerTreeNode - OS: Linux 
2020-08-05 15:15:17,729 [ 169329]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'aFileName' of com/intellij/openapi/util/io/FileUtil.toSystemDependentName must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'aFileName' of com/intellij/openapi/util/io/FileUtil.toSystemDependentName must not be null
        at com.intellij.openapi.util.io.FileUtil.$$$reportNull$$$0(FileUtil.java)
        at com.intellij.openapi.util.io.FileUtil.toSystemDependentName(FileUtil.java)
        at com.jetbrains.plugins.webDeployment.config.WebServerConfig.getRootPath(WebServerConfig.java:600)
        at com.jetbrains.plugins.webDeployment.config.ServerBaseDeployable.getRootPath(ServerBaseDeployable.java:302)
        at com.jetbrains.plugins.webDeployment.config.ServerPasswordSafeDeployable.getRootPath(ServerPasswordSafeDeployable.java:11)
        at com.jetbrains.plugins.webDeployment.ui.remotebrowser.ServerTreeNode.<init>(ServerTreeNode.java:84)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserForm.initialize(ServerBrowserForm.java:78)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserForm.<init>(ServerBrowserForm.java:66)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.createCenterPanel(ServerBrowserDialog.java:71)
        at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1338)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.init(ServerBrowserDialog.java:56)
        at com.jetbrains.plugins.webDeployment.ui.ServerBrowserDialog.<init>(ServerBrowserDialog.java:50)
        at fr.adrienbrault.idea.symfony2plugin.ui.utils.UiSettingsUtil.openFileDialogForDefaultWebServerConnection(UiSettingsUtil.java:66)
        at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm$3.actionPerformed(ContainerSettingsForm.java:146)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
        at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
        at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
        at java.desktop/java.awt.Component.processEvent(Component.java:6415)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:904)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:733)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:710)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:80)
        at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:888)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-08-05 15:15:17,732 [ 169332]  ERROR - llij.ide.plugins.PluginManager - PhpStorm 2020.2  Build #PS-202.6397.115 
2020-08-05 15:15:17,732 [ 169332]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-08-05 15:15:17,732 [ 169332]  ERROR - llij.ide.plugins.PluginManager - OS: Linux `
