### ISSUE TITLE
java.lang.Throwable: The method designed for fully qualified names only.

### ISSUE THREAD

**Issue by artspb** [Haehnchen/idea-php-symfony2-plugin#1139]
We've got the exception from one of the PhpStorm users. 

<details>
  <summary>java.lang.Throwable: The method designed for fully qualified names only. Got "Symfony\Component\HttpKernel\Event\FilterControllerArgumentsEvent".</summary>
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.jetbrains.php.util.PhpContractUtil.assertFqn(PhpContractUtil.java:19)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.createQualifiedName(PhpCodeInsightUtil.java:522)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.createQualifiedName(PhpCodeInsightUtil.java:589)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.createQualifiedName(PhpCodeInsightUtil.java:574)
	at fr.adrienbrault.idea.symfony2plugin.util.AnnotationBackportUtil.getQualifiedName(AnnotationBackportUtil.java:156)
	at fr.adrienbrault.idea.symfony2plugin.config.yaml.inspection.EventMethodCallInspection$MyCreateMethodQuickFix.getEventTypeHint(EventMethodCallInspection.java:207)
	at fr.adrienbrault.idea.symfony2plugin.config.yaml.inspection.EventMethodCallInspection$MyCreateMethodQuickFix.getStringBuilder(EventMethodCallInspection.java:180)
	at fr.adrienbrault.idea.symfony2plugin.codeInspection.quickfix.CreateMethodQuickFix.applyFix(CreateMethodQuickFix.java:61)
	at fr.adrienbrault.idea.symfony2plugin.codeInspection.quickfix.CreateMethodQuickFix.applyFix(CreateMethodQuickFix.java:25)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:88)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:181)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$3(ShowIntentionActionsHandler.java:209)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:211)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$1(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$2(ShowIntentionActionsHandler.java:185)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:184)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$1(IntentionListStep.java:293)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</details>

**Comment by artspb** [comment]
Still relevant.

**Comment by artspb** [comment]
Still relevant.
