### ISSUE TITLE
Exception in Symfony Plugin

### ISSUE THREAD

**Issue by lashae** [Haehnchen/idea-php-symfony2-plugin#1174]
I'm not sure whether I should report it here or elsewhere, if there is some other place I'd be glad to be informed ;-)

Unfortunately I don't have a "steps to reproduce" info since exception occured right after I opened a project in PhpStorm.

Trace is as follows:

```
Already disposed: Project (Disposed) Api
java.lang.AssertionError: Already disposed: Project (Disposed) Api
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:247)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:43)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:245)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:238)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:44)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by Gamesh** [comment]
I noticed that this usually occurs when you close one project that uses symfony and this plugin is enabled and open anther one with symfony. Then it reports that the old project is already disposed.

```
Already disposed: Project (Disposed) mds
java.lang.AssertionError: Already disposed: Project (Disposed) mds
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:247)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:43)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:245)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:238)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:44)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by oleg-andreyev** [comment]
Duplicated by #1309 #1268 #1229

**Comment by oleg-andreyev** [comment]
It seems that Symfony Plugin is trying to fetch something from remote server even when nothing was configured to a remote server.

**Comment by Haehnchen** [comment]
was moved to proper / new extension points
