### ISSUE TITLE
Generating service issue in services.xml with Shopware 

### ISSUE THREAD

**Issue by Schuchie** [Haehnchen/idea-php-symfony2-plugin#1182]
PHPStorm Version: 2018.1.2
OS: Win 10 Pro 64Bit

I'm getting the following error on generating a service in services.xml. Sometimes it works, but then is the service id missing. In addition i am using shopware.

`0 > -1
java.lang.IllegalArgumentException: 0 > -1
	at java.util.Arrays.copyOfRange(Arrays.java:3480)
	at java.util.Arrays.copyOfRange(Arrays.java:3441)
	at fr.adrienbrault.idea.symfony2plugin.action.generator.naming.DefaultServiceNameStrategy.getServiceName(DefaultServiceNameStrategy.java:45)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getServiceNameForClass(ServiceUtil.java:556)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.updateTask(SymfonyCreateService.java:365)
	at java.lang.Thread.run(Thread.java:745)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.update(SymfonyCreateService.java:344)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.lambda$init$0(SymfonyCreateService.java:107)
	at fr.adrienbrault.idea.symfony2plugin.ui.utils.ClassCompletionPanelWrapper$1.lambda$documentChanged$0(ClassCompletionPanelWrapper.java:65)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.n(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at java.awt.Component.show(Component.java:1679)
	at java.awt.Component.setVisible(Component.java:1631)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:998)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.prepare(SymfonyCreateService.java:582)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.create(SymfonyCreateService.java:588)
	at fr.adrienbrault.idea.symfony2plugin.action.generator.ServiceGenerateAction.invokeFile(ServiceGenerateAction.java:115)
	at fr.adrienbrault.idea.symfony2plugin.action.generator.ServiceGenerateAction.access$200(ServiceGenerateAction.java:27)
	at fr.adrienbrault.idea.symfony2plugin.action.generator.ServiceGenerateAction$1.invoke(ServiceGenerateAction.java:62)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:79)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:71)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:908)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:898)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:892)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1398)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2882)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:173)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:190)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:56)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1392)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:307)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:338)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:169)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:144)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:442)
	at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:396)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:337)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:250)
	at com.intellij.ui.popup.WizardPopup.a(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:126)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:160)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:87)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by githoober** [comment]
I am getting the same error too:

    java.lang.IllegalArgumentException: 0 > -1
	at java.util.Arrays.copyOfRange(Arrays.java:3480)
	at java.util.Arrays.copyOfRange(Arrays.java:3441)
	at fr.adrienbrault.idea.symfony2plugin.action.generator.naming.DefaultServiceNameStrategy.getServiceName(DefaultServiceNameStrategy.java:45)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getServiceNameForClass(ServiceUtil.java:556)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.updateTask(SymfonyCreateService.java:365)
	at java.lang.Thread.run(Thread.java:745)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.update(SymfonyCreateService.java:344)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.lambda$init$0(SymfonyCreateService.java:107)
	at fr.adrienbrault.idea.symfony2plugin.ui.utils.ClassCompletionPanelWrapper.setClassName(ClassCompletionPanelWrapper.java:49)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.initClassName(SymfonyCreateService.java:234)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.init(SymfonyCreateService.java:183)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.prepare(SymfonyCreateService.java:571)
	at fr.adrienbrault.idea.symfony2plugin.action.ui.SymfonyCreateService.create(SymfonyCreateService.java:592)
	at fr.adrienbrault.idea.symfony2plugin.action.SymfonyContainerServiceBuilder.actionPerformed(SymfonyContainerServiceBuilder.java:81)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
