### ISSUE TITLE
com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.MethodReference

### ISSUE THREAD

**Issue by oleg-andreyev** [Haehnchen/idea-php-symfony2-plugin#119]
Not very sure who is responsible for this, but seems that exception was raised in plugin. Currently I don't have an idea how to reproduce issue it just happens time to time

Stacktrace:

```
com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.MethodReference:
com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.MethodReference
java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.MethodReference
    at fr.adrienbrault.idea.symfony2plugin.form.FormTypeReferenceContributor$1.getReferencesByElement(FormTypeReferenceContributor.java:46)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:119)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:65)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:57)
    at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:329)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
    at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.findReferenceAt(MultiplePsiFilesPerDocumentFileViewProvider.java:171)
    at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:567)
    at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:114)
    at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:302)
    at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:201)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:97)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:345)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

Using phpStorm 6.0.3 with Symfony2 Plugin 0.9.11

**Comment by kamelkimiaei** [comment]
this error happens in "idea-php-laravel-plugin" also

**Comment by cjthomp** [comment]
Yep, started happening for me, 2016.1.2. laravel plugin with _ide_helper

**Comment by svetdev** [comment]
@cjthomp Have you been able to fix this errors? I started getting them in latest laravel plugin too.
