### ISSUE TITLE
Problem with symfony plugin in PhpStorm PS-182.3208.33

### ISSUE THREAD

**Issue by vkhramtsov** [Haehnchen/idea-php-symfony2-plugin#1191]
Hello,

After update PhpStorm to version  PS-182.3208.33 I have problem with symfony plugin. Stack trace is:
```
java.lang.NoClassDefFoundError: Could not initialize class fr.adrienbrault.idea.symfony2plugin.Symfony2Icons
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.classNameMarker(ServiceLineMarkerProvider.java:92)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:66)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:197)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Thank you.

P.S. It can be related to #1190

**Comment by cedricziel** [comment]
I highly supect it's solved with #1164 already, but this pr isnt part of any release yet.

@Haehnchen can would you be able to tag a new release?

**Comment by matiux** [comment]
@vkhramtsov I have same issue with the same version of PhpStorm :(

**Comment by cedricziel** [comment]
You can try to build the plugin yourself:

* have a JDK installed
* clone the repo, checkout master
* run `./gradlew buildPlugin`
* manually install the jar contained in build/distributions

This is relatively straight forward.

**Comment by vkhramtsov** [comment]
@cedricziel @Haehnchen I think that we need release, because it is better to fix this issue for all users. Of course I can build this plugin and upload it somewhere, but I don't think that it is so good idea.

**Comment by cedricziel** [comment]
Sure thing, I just wanted to let you know if you want to try it.

**Comment by cedricziel** [comment]
Confirmed, the current master fixes these issues.

FWIW: Here's a current build: 
[Symfony Plugin-0.16.165.zip](https://github.com/Haehnchen/idea-php-symfony2-plugin/files/2105496/Symfony.Plugin-0.16.165.zip).

Nevertheless, don't trust a random guy on tghe internet and try to build it yourself as outlined above.

**Comment by vkhramtsov** [comment]
@cedricziel Thank you for you help and patience

**Comment by vkhramtsov** [comment]
Currenty I don't have issue anymore. I've updated phpstorm and plugins. Currently I have `PhpStorm 2018.2 EAP Build #PS-182.3341.34`.

Closing issue
