### ISSUE TITLE
Already disposed: Project (Disposed) app

### ISSUE THREAD

**Issue by oleg-andreyev** [Haehnchen/idea-php-symfony2-plugin#1229]
Stacktrace
<details>

```
java.lang.AssertionError: Already disposed: Project (Disposed) app
	at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:45)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:42)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
</details>

PhpStorm 2018.2.3
Build #PS-182.4323.68, built on September 13, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by cedricziel** [comment]
`Already disposed` errors might happen when a project is closed while loading. Not entirely sure what the `WebDeploymentProjectComponent` does - can someone explain it to me, so I can (possibly) fix it?

**Comment by Haehnchen** [comment]
was moved to proper / new extension points
