### ISSUE TITLE
Cant load symfony versions when creating a new project

### ISSUE THREAD

**Issue by savio-code** [Haehnchen/idea-php-symfony2-plugin#1230]
When loading a new symfony project, the versions arent displayed, hence a project cannot be created.  Below is the error generated. Has something to do with malformed json from server

com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerUtil.getVersions(SymfonyInstallerUtil.java:114)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerForm.getVersions(SymfonyInstallerForm.java:54)
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerForm.lambda$appendSymfonyVersions$3(SymfonyInstallerForm.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 10 more

**Comment by cedricziel** [comment]
Fixed in #1227 already. All we need is a new release.

**Comment by savio-code** [comment]
Ok, please when will new release be ready

**Comment by cedricziel** [comment]
Closed via #1227 

Release will follow in the next days.
