### ISSUE TITLE
java.lang.AssertionError: Already disposed: Project (Disposed)

### ISSUE THREAD

**Issue by metaer** [Haehnchen/idea-php-symfony2-plugin#1268]
java.lang.AssertionError: Already disposed: Project (Disposed) project_name
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:245)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:236)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:46)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:100)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by Haehnchen** [comment]
was moved to proper / new extension points
