### ISSUE TITLE
Crash for pre-3.4 class const syntax autocompletion in YAML

### ISSUE THREAD

**Issue by d1823** [Haehnchen/idea-php-symfony2-plugin#1283]
Hey. Just managed to crash the Symfony Plugin.

The crash happened when I invoked autocompletion for PHP class constant from within the YAML file using the pre 3.4 syntax according to this: https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

PHPStorm Version: 2018.3.4 (183.5429.47)
Plugin Version: 0.17.170

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at fr.adrienbrault.idea.symfony2plugin.dic.container.util.ServiceContainerUtil.getTargetsForConstant(ServiceContainerUtil.java:565)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:47)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLScalarImpl.accept(YAMLScalarImpl.java:183)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLSequenceItemImpl.accept(YAMLSequenceItemImpl.java:52)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:47)
	at org.jetbrains.yaml.psi.impl.YAMLSequenceImpl.accept(YAMLSequenceImpl.java:41)
	at org.jetbrains.yaml.psi.impl.YAMLBlockSequenceImpl.accept(YAMLBlockSequenceImpl.java:19)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:216)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:47)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:216)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:47)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:216)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:47)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:216)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLCompoundValueImpl.accept(YAMLCompoundValueImpl.java:47)
	at org.jetbrains.yaml.psi.impl.YAMLMappingImpl.accept(YAMLMappingImpl.java:78)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$2.visitElement(ContainerConstantInspection.java:53)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLDocumentImpl.accept(YAMLDocumentImpl.java:37)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:730)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection.yamlVisitor(ContainerConstantInspection.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection.access$100(ContainerConstantInspection.java:22)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.ContainerConstantInspection$1.visitFile(ContainerConstantInspection.java:34)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$7(LocalInspectionsPass.java:316)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1163)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:328)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:199)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Haehnchen** [comment]
was already fixed via #1640
