### ISSUE TITLE
PhpStorm 2019.2 Plugin Exception

### ISSUE THREAD

**Issue by foxviewr** [Haehnchen/idea-php-symfony2-plugin#1358]
An exception occurs in the new **2019.2** version of **PhpStorm**, making the Plugin not work correctly. 

For example, on a _Controller_ file, it fails to find the usages of a function _Action_ to it's respective `.yml` routing configuration file.

Here's my `stacktrace.txt` data of the Exception:

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@32357ff1 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3de64903
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@32357ff1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@43d3b183] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3de64903, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@29cb4801]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:67)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:250)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getNamespaces(ConfigAddPathTwigNamespaces.java:49)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1316)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1306)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateFiles(TwigUtil.java:1012)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplatePsiElements(TwigUtil.java:1078)
	at fr.adrienbrault.idea.symfony2plugin.navigation.controller.TemplatesControllerRelatedGotoCollector.visitMethodTemplateNames(TemplatesControllerRelatedGotoCollector.java:96)
	at fr.adrienbrault.idea.symfony2plugin.navigation.controller.TemplatesControllerRelatedGotoCollector.collectGotoRelatedItems(TemplatesControllerRelatedGotoCollector.java:37)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.getGotoRelatedItems(ControllerMethodLineMarkerProvider.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.collect(ControllerMethodLineMarkerProvider.java:49)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.collectSlowLineMarkers(ControllerMethodLineMarkerProvider.java:108)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Hope this helps.

**Comment by mmi1** [comment]
Same to me... PhpStorm 2019.2 and it has been appearing permanently fr the last month or so.... 

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@25865f39 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@d305b4d
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@25865f39] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@d305b4d]
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
    at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:67)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:250)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getNamespaces(ConfigAddPathTwigNamespaces.java:49)
    at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1316)
    at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1242)
    at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1230)
    at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigFileMethodUsageOnIndex(TwigUtil.java:754)
    at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachController(TwigLineMarkerProvider.java:103)
    at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:58)
    at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
    at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
    at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
    at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by matatirosolutions** [comment]
For reference I'm still receiving this error with PHPStorm 2019.2 and the latest plugin build (0.19.184)

**Comment by polnetwork** [comment]
I'm also getting this error on PhpStorm 2019.2.4 and I'm not able to send the Issue.  
Build #PS-192.7142.41, built on October 30, 2019

**Comment by magus424** [comment]
Just started getting this error today while editing a twig file.

Symfony plugin 0.19.189, PhpStorm 2019.2.5
Build #PS-192.7142.51, built on November 13, 2019

**Comment by siller444** [comment]
I'm also getting this error.
Symfony Support 0.19.189 Jan 12, 2020
Build #PS-193.6015.48, built on January 22, 2020

How to fix it?

**Comment by Rho-bur** [comment]
Hello,
Thank you for your work on this plugin and sharing it freely!
Since the latest PhpStorm upgrade I get
```java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@19973cbc != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50efcb28
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@19973cbc] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50efcb28]

Recomputation gives com.intellij.util.CachedValueBase$Data@3f5552ca which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:82)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:250)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getNamespaces(ConfigAddPathTwigNamespaces.java:49)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1345)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1335)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateFiles(TwigUtil.java:1041)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplatePsiElements(TwigUtil.java:1107)
	at fr.adrienbrault.idea.symfony2plugin.navigation.controller.TemplatesControllerRelatedGotoCollector.collectGotoRelatedItems(TemplatesControllerRelatedGotoCollector.java:28)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.getGotoRelatedItems(ControllerMethodLineMarkerProvider.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.collect(ControllerMethodLineMarkerProvider.java:49)
	at fr.adrienbrault.idea.symfony2plugin.dic.ControllerMethodLineMarkerProvider.collectSlowLineMarkers(ControllerMethodLineMarkerProvider.java:108)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:193)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:95)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)```
Screenshot: https://i.imgur.com/1rZy6IK.png
Hope it helps!
All the best,
Robert

**Comment by yura3d** [comment]
@Haehnchen Hi! Are there any news on this issue? Still see it at least several times per day.
Plugin version 0.20.197 (latest)
PhpStorm 2020.1.2 (latest stable)

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1b936abc != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6cc38b8e
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1b936abc] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6cc38b8e]

Recomputation gives com.intellij.util.CachedValueBase$Data@2c8c969b which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:91)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:78)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getNamespaces(ConfigAddPathTwigNamespaces.java:43)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1339)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1329)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateFiles(TwigUtil.java:1035)
	at fr.adrienbrault.idea.symfony2plugin.templating.inspection.TwigTemplateMissingInspection.invoke(TwigTemplateMissingInspection.java:46)
	at fr.adrienbrault.idea.symfony2plugin.templating.inspection.TwigTemplateMissingInspection.access$000(TwigTemplateMissingInspection.java:24)
	at fr.adrienbrault.idea.symfony2plugin.templating.inspection.TwigTemplateMissingInspection$1.visitElement(TwigTemplateMissingInspection.java:35)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:69)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:60)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$3(LocalInspectionsPass.java:266)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:155)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:147)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$4(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:265)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mitelg** [comment]
@Haehnchen error still occurs on 
```
PhpStorm 2021.1.2
Build #PS-211.7142.44, built on April 30, 2021
Subscription is active until February 2, 2022.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-50-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), tv.twelvetone.intellij.plugins.intellivue (1.1.0), NEON support (0.5.1), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.11.2), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209), ru.adelf.idea.dotenv (2021.1)
Current Desktop: ubuntu:GNOME
```
Plugin version is current `0.23.209`

This issue is duplicated by #1532 and #1554
