### ISSUE TITLE
Exception in plugin v. 0.19.184 - Virtual file doesn't support id: LightVirtualFile

### ISSUE THREAD

**Issue by sabat24** [Haehnchen/idea-php-symfony2-plugin#1381]
It occured 2 times since last upgrade (yesterday). I don't know what is important here, this is why I pasted whole information received from phpStorm.

```
java.lang.IllegalArgumentException: Virtual file doesn't support id: LightVirtualFile: \panel.html.twig, implementation class: com.intellij.testFramework.LightVirtualFile
	at com.intellij.util.indexing.FileBasedIndex.getFileId(FileBasedIndex.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:653)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.visitParentFiles(TwigFileUtil.java:63)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.collectParentFiles(TwigFileUtil.java:43)
	at fr.adrienbrault.idea.symfony2plugin.twig.loader.FileOverwritesLazyLoader.getFiles(FileOverwritesLazyLoader.java:46)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigBlockUtil.hasBlockOverwrites(TwigBlockUtil.java:149)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachBlockOverwrites(TwigLineMarkerProvider.java:283)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by vkost** [comment]
Same here

**Comment by mturalenka** [comment]
same here, any news?
PhpStorm 2019.2.2
Build #PS-192.6603.42, built on September 12, 2019

Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by markus-fischbacher** [comment]
I'm facing the same issue.
IntelliJ IDEA 2019.2.3
MacOS 10.15

**Comment by equapro** [comment]
Same issue

PhpStorm 2019.2.3
Build #PS-192.6817.20, built on September 25, 2019

MacOS 10.14.6

**Comment by COil** [comment]
Same here :

GoLand 2019.2.3
Build #GO-192.6817.25, built on October 2, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-65-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=TRUE
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv, net.ashald.envfile

**Comment by driq** [comment]
For what it's worth, same issue here:

```
java.lang.IllegalArgumentException: Virtual file doesn't support id: LightVirtualFile: /viewAssignment.html.twig, implementation class: com.intellij.testFramework.LightVirtualFile
	at com.intellij.util.indexing.FileBasedIndex.getFileId(FileBasedIndex.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:653)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.visitParentFiles(TwigFileUtil.java:63)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigFileUtil.collectParentFiles(TwigFileUtil.java:43)
	at fr.adrienbrault.idea.symfony2plugin.twig.loader.FileOverwritesLazyLoader.getFiles(FileOverwritesLazyLoader.java:46)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigBlockUtil.hasBlockOverwrites(TwigBlockUtil.java:149)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachBlockOverwrites(TwigLineMarkerProvider.java:283)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:194)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

```
PhpStorm 2019.2.4
Build #PS-192.7142.41, built on October 30, 2019
Licensed to Karify B.V. / Hendrik Wouters
Subscription is active until May 2, 2020
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-19-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1923M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.intellij.ideolog, com.dmarcotte.handlebars, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv
```

**Comment by ruudk** [comment]
Is there a way to reproduce this?

**Comment by driq** [comment]
I get it when i do a diff (ctrl-d in the version control tab) on a specific twig file. I'm trying to figure out what it is in the file that triggers the error, so that I can send a sample.

**Comment by tom-reinders** [comment]
Same here

```
PhpStorm 2019.3 EAP
Build #PS-193.4932.16, built on October 31, 2019
PhpStorm EAP User
Expiration date: November 30, 2019
Runtime version: 11.0.4+10-b520.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.16-100.fc28.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1921M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.dmarcotte.handlebars, com.github.masahirosuzuka.PhoneGapIntelliJPlugin, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.laravel, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.jetbrains.plugins.node-remote-interpreter, ru.adelf.idea.dotenv
```
