### ISSUE TITLE
java.lang.ClassCastException exception on indexing

### ISSUE THREAD

**Issue by MaXal** [Haehnchen/idea-php-symfony2-plugin#1410]
The following commit: https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/63fb7218b23c1791e4eeb51400a0d9c82cc2fed8

Introduces the following exception:
```
java.lang.ClassCastException: class com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to class com.jetbrains.php.lang.psi.elements.StringLiteralExpression (com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl and com.jetbrains.php.lang.psi.elements.StringLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3348dfec)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.PhpMethodVariableResolveUtil$TemplateRenderPsiRecursiveElementWalkingVisitor.resolveString(PhpMethodVariableResolveUtil.java:352)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.PhpMethodVariableResolveUtil$TemplateRenderPsiRecursiveElementWalkingVisitor.visitMethodReference(PhpMethodVariableResolveUtil.java:334)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.PhpMethodVariableResolveUtil$TemplateRenderPsiRecursiveElementWalkingVisitor.visitElement(PhpMethodVariableResolveUtil.java:280)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:34)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.PhpMethodVariableResolveUtil$TemplateRenderPsiRecursiveElementWalkingVisitor.visitElement(PhpMethodVariableResolveUtil.java:284)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:197)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.PhpMethodVariableResolveUtil.visitRenderTemplateFunctions(PhpMethodVariableResolveUtil.java:263)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.PhpTwigTemplateUsageStubIndex.lambda$getIndexer$2(PhpTwigTemplateUsageStubIndex.java:50)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:139)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1706)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$33(FileBasedIndexImpl.java:1634)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:698)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1614)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1600)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:114)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$1(CacheUpdateRunner.java:207)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$2(CacheUpdateRunner.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:577)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:523)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:149)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$createRunnable$3(CacheUpdateRunner.java:220)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:198)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:237)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by Haehnchen** [comment]
fixed
