### ISSUE TITLE
com.intellij.util.indexing.FileContentImpl$IllegalDataException on indexing

### ISSUE THREAD

**Issue by MaXal** [Haehnchen/idea-php-symfony2-plugin#1459]
Since version `0.19.192` the exception is thrown on indexing.

It looks like it's caused by `6826000848b1bc192d5794997933e6c4de9d248a` (_wrapped the deprecated "getBaseDir" for getting the project root directory_)

The following exception is thrown:
```
Exception occurred during the run
com.intellij.util.indexing.FileContentImpl$IllegalDataException: Cannot obtain text for binary file type : Unknown
	at com.intellij.util.indexing.FileContentImpl.getContentAsText(FileContentImpl.java:196)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:78)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:246)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:66)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.TranslationStubIndex$1.getXlfStringMap(TranslationStubIndex.java:100)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.TranslationStubIndex$1.map(TranslationStubIndex.java:47)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.TranslationStubIndex$1.map(TranslationStubIndex.java:37)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:150)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$20(FileBasedIndexImpl.java:1181)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:723)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1161)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1147)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$2(UnindexedFilesUpdater.java:130)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$1(CacheUpdateRunner.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$2(CacheUpdateRunner.java:224)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$createRunnable$3(CacheUpdateRunner.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:198)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by jurgenhaas** [comment]
Same issue here, glad to see a fix already being merged. Am I right that there is no new release yet?

**Comment by anotherjames** [comment]
I downloaded the previously-working version (1.19.191) from https://plugins.jetbrains.com/plugin/7219-symfony-support/versions, and installed that as a plugin from disk. Now works fine for me. When a new release arrives including the fix, I'll gladly update properly.

**Comment by anotherjames** [comment]
1.19.193 is now available, includes the fix, and seems to work :-) Thanks @Haehnchen!
