### ISSUE TITLE
Exception at launch

### ISSUE THREAD

**Issue by mediproductions** [Haehnchen/idea-php-symfony2-plugin#1492]
Hi,
when I launch phpstorm with this plugin, I get this exception (symfony support 0.20.196 phpstorm 2020.1.2) :
```
java.lang.ClassCastException: class org.jetbrains.plugins.textmate.psi.TextMateFile cannot be cast to class org.jetbrains.yaml.psi.YAMLFile (org.jetbrains.plugins.textmate.psi.TextMateFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @359003d7; org.jetbrains.yaml.psi.YAMLFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @48da5fce)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getTwigPaths(ConfigAddPathTwigNamespaces.java:62)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.lambda$getNamespaces$0(ConfigAddPathTwigNamespaces.java:46)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:72)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.ConfigAddPathTwigNamespaces.getNamespaces(ConfigAddPathTwigNamespaces.java:43)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1339)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1329)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateMapProxy(TwigUtil.java:936)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.access$200(TwigUtil.java:81)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil$MyAllTemplateFileMapCachedValueProvider.compute(TwigUtil.java:2822)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:72)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateMap(TwigUtil.java:912)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateMap(TwigUtil.java:897)
	at fr.adrienbrault.idea.symfony2plugin.navigation.TemplateFileContributor.getNames(TemplateFileContributor.java:24)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:127)
	at com.intellij.ide.actions.GotoFileItemProvider.processNames(GotoFileItemProvider.java:135)
	at com.intellij.ide.actions.GotoFileItemProvider.processItemsForPattern(GotoFileItemProvider.java:103)
	at com.intellij.ide.actions.GotoFileItemProvider.doFilterElements(GotoFileItemProvider.java:83)
	at com.intellij.ide.actions.GotoFileItemProvider.lambda$filterElementsWithWeights$0(GotoFileItemProvider.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElementsWithWeights(GotoFileItemProvider.java:64)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:245)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:579)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:275)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.lambda$run$1(MultiThreadSearcher.java:177)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.run(MultiThreadSearcher.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:198)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Haehnchen** [comment]
fixed
