### ISSUE TITLE
"Cannot nest groups" error in services.yaml exclusion glob

### ISSUE THREAD

**Issue by Wait4Code** [Haehnchen/idea-php-symfony2-plugin#1517]
Hi,
I have some IDE Fatal errors because of a configuration I made in services.yaml.
```yml
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Service/{IspConfiguration,DataCollection}}'
```

See the nested group in the exclude glob pattern. It seems that this plugin does not handle that case...

```
java.util.regex.PatternSyntaxException: Cannot nest groups near index 130
[file_path...]/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Service/{IspConfiguration,DataCollection}}**
                                                                                                                                  ^
	at java.base/sun.nio.fs.Globs.toRegexPattern(Globs.java:152)
	at java.base/sun.nio.fs.Globs.toWindowsRegexPattern(Globs.java:215)
	at java.base/sun.nio.fs.WindowsFileSystem.getPathMatcher(WindowsFileSystem.java:268)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.isMatchingGlobResource(ServiceIndexUtil.java:281)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.matchesResourcesGlob(ServiceIndexUtil.java:197)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.matchesResourcesGlob(ServiceIndexUtil.java:201)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.findServiceDefinitionsOfResourceLazy(ServiceIndexUtil.java:254)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.classNameMarker(ServiceLineMarkerProvider.java:126)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:77)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:195)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:410)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Wait4Code** [comment]
It seems that last released version fixes this bug. At least I don't see the ugly blinking red icon anymore. Thanks !
