### ISSUE TITLE
Non-idempotent computation

### ISSUE THREAD

**Issue by zsolt-szilagyi** [Haehnchen/idea-php-symfony2-plugin#1532]
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@174294de != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@21d23bd1
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@174294de] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@21d23bd1]

Recomputation gives com.intellij.util.CachedValueBase$Data@61ecce1c which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:91)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:78)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:154)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespacesInner(JsonFileIndexTwigNamespaces.java:55)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.lambda$getNamespaces$0(JsonFileIndexTwigNamespaces.java:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespaces(JsonFileIndexTwigNamespaces.java:42)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1339)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1265)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplatesExtendingFile(TwigUtil.java:2170)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplatesExtendingFile(TwigUtil.java:2158)
	at fr.adrienbrault.idea.symfony2plugin.twig.loader.FileImplementsLazyLoader.getFiles(FileImplementsLazyLoader.java:35)
	at fr.adrienbrault.idea.symfony2plugin.twig.utils.TwigBlockUtil.hasBlockImplementations(TwigBlockUtil.java:66)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.attachBlockImplements(TwigLineMarkerProvider.java:237)
	at fr.adrienbrault.idea.symfony2plugin.templating.TwigLineMarkerProvider.collectSlowLineMarkers(TwigLineMarkerProvider.java:88)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:195)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by gggeek** [comment]
Happening with PhpStorm 2021.1 / plugin version 0.22.207:

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@21b45126 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@23a2271a
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@21b45126, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@42824258, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@30478968, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@33f9c327, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1d1a8b5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5111aa55, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5d9175d6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@208c65b8, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2c14e51c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@700bb1c9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@26e255db, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6580551a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6eb770b3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@439f1155, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77e7d870, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@10287b13, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@454fb34d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7ee10708, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@378c74fc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@64af61fd, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5cc273fe, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2a6de629, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7e125c0c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@612d7aba, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2e3fb8e2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6b265fa2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7388cf6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@d4ade01, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5ee19fe2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7e310d3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@447f73e5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1f1e07bd, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4dd29533, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@52a861d2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6d77c039, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2bb11c5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5b9967ac, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4aae3bfc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@198b5c98, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@43644355, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5350e892, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@689a58df, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2b36a6c8, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4a292610, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1e6953bf, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@248fbc0d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3a915eb2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@390be656, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6d2bae63, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@341d181f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4c9b4e0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6216cb79, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@527e29ee, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@e7f1e5e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@47d8d5c5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@13419344, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@30d3e99b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@46288c31, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@47df0fcc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@589b7fc0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77abda79, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@75e089b9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4a7e59a6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@49985a56, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6049390e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1115c9ff] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@23a2271a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@299e1112, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@225fb49d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@b776891, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@34920231, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6d5d8330, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@32f9295a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@27afc74, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@26dde580, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2718b668, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5c50f828, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@99c268a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@402423dc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@226d6646, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@79a74b9b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@11679a53, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@70bc6160, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@39aa7667, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7a12095a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@578aa149, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@442e6db9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2edd2215, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@44efa64d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@46edc770, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@711939b1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3613700d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@ff7754c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2789f585, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1fe59474, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@325b0c9d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@632528f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6e7fba11, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5d8ad59e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@37df0556, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@236d8f08, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@30d11646, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3bfc13e7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@74c6547b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3b9c9024, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@347c237, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@58ff8a93, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1e5c787b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@411ed624, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7c75f24a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@58fa4445, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@25987081, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@12803de0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@41b47a58, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4be6d647, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2d9cbbc2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3ee0ecac, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5ce43792, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@21cd86a7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@69476bf7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50fb7fff, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2dde9ad5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@606bc977, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@32a11e5e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@39ae9b72, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@60ffa6a0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5e61fbb9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@64085dc5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@29303f3d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3467461d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@650acf1b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@434a400a]

Recomputation gives com.intellij.util.CachedValueBase$Data@6bab5689 which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespacesInner(JsonFileIndexTwigNamespaces.java:55)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.lambda$getNamespaces$0(JsonFileIndexTwigNamespaces.java:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespaces(JsonFileIndexTwigNamespaces.java:42)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1343)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1269)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1257)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigFileMethodUsageOnIndex(TwigUtil.java:784)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.hasController(TwigIconProvider.java:57)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.getIcon(TwigIconProvider.java:33)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:419)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gggeek** [comment]
PS: same as #1154, #1358 ?

**Comment by MarslMarcello** [comment]
HI getting a similar error. I thought and update could solve it, so I did it to the latest version and now on PHPStorm 2021.1.2 and Plugin version 0.23.208 still the issue.

`java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7c4869f1 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@49899dc2
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7c4869f1] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@49899dc2]

Recomputation gives com.intellij.util.CachedValueBase$Data@49af4f1c which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespacesInner(JsonFileIndexTwigNamespaces.java:55)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.lambda$getNamespaces$0(JsonFileIndexTwigNamespaces.java:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespaces(JsonFileIndexTwigNamespaces.java:42)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1343)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1269)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1257)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigFileMethodUsageOnIndex(TwigUtil.java:784)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.hasController(TwigIconProvider.java:57)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.getIcon(TwigIconProvider.java:33)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:419)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Haehnchen** [comment]
duplicate: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1554
