### ISSUE TITLE
Search everywhere feature is getting stuck 

### ISSUE THREAD

**Issue by norberttech** [Haehnchen/idea-php-symfony2-plugin#1537]
Hey,
so first of all, thanks for this amazing plugin, it makes my life really easier! 🍻
Some time ago I noticed that feature "Search Everywhere" in the IDE (I'm using IntelliJ 2020.2) is getting stuck from time to time and by stuck I mean I can't trigger the dialog, neither through the button in the UI or through the shortcut. 
![image](https://user-images.githubusercontent.com/1921950/91160711-0a5ef900-e6ca-11ea-9ecf-e1d04d2be0b2.png)

I reported this incident to JetBrains and their engineers helped to identify that it's actually related to this plugin. 

The recommended to provide plugin author following logs: 

<details><summary><strong>Logs</strong></summary>
<p>

```
2020-08-19 09:47:48,205 [51908324]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:47:48,206 [51908325]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:47:48,207 [51908326]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:47:48,228 [51908347]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:48:50,749 [51970868]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.twig.variable.globals.TwigGlobalsServiceParser 
2020-08-19 09:48:50,750 [51970869]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:48:50,751 [51970870]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:48:50,781 [51970900]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.twig.variable.globals.TwigGlobalsServiceParser 
2020-08-19 09:50:38,594 [52078713]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:50:38,595 [52078714]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:38,596 [52078715]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:38,616 [52078735]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:50:38,616 [52078735]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.twig.variable.globals.TwigGlobalsServiceParser 
2020-08-19 09:50:38,617 [52078736]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:38,618 [52078737]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:38,637 [52078756]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.twig.variable.globals.TwigGlobalsServiceParser 
2020-08-19 09:50:39,075 [52079194]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:50:39,076 [52079195]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:39,076 [52079195]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:39,089 [52079208]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:50:39,090 [52079209]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:50:39,091 [52079210]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:39,092 [52079211]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:39,105 [52079224]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:50:46,308 [52086427]   INFO -                 Symfony-Plugin - update routing: /xxxxxxxxxxxxxx/var/cache/dev/UrlGenerator.php 
2020-08-19 09:50:46,346 [52086465]   INFO -                 Symfony-Plugin - update routing: /xxxxxxxxxxxxxx/var/cache/dev/UrlMatcher.php 
2020-08-19 09:50:46,358 [52086477]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.doctrine.component.EntityNamesServiceParser 
2020-08-19 09:50:46,358 [52086477]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:46,359 [52086478]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:46,371 [52086490]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.doctrine.component.EntityNamesServiceParser 
2020-08-19 09:50:46,371 [52086490]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.doctrine.component.DocumentNamespacesParser 
2020-08-19 09:50:46,371 [52086490]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:46,372 [52086491]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:46,387 [52086506]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.doctrine.component.DocumentNamespacesParser 
2020-08-19 09:50:59,127 [52099246]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:50:59,128 [52099247]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:59,129 [52099248]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:50:59,149 [52099268]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:52:36,149 [52196268]  ERROR - tellij.psi.PsiReferenceService - IdeaLoggingEvent[message=Reference element is not the same element for which references were queried, throwable=java.lang.RuntimeException: Element: com.intellij.psi.impl.source.xml.XmlTokenImpl; reference: fr.adrienbrault.idea.symfony2plugin.config.xml.ParameterXmlReference; reference element: com.intellij.psi.impl.source.xml.XmlTextImpl
    at com.intellij.psi.PsiReferenceServiceImpl.assertReferencesHaveSameElement(PsiReferenceServiceImpl.java:51)
    at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
    at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:938)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:87)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:178)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:204)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:177)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:934)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:241)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:225)
    at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
    at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$4(JobLauncherImpl.java:135)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$5(JobLauncherImpl.java:131)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:835)
    at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:142)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:40)
    at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.bulkProcessElementsWithWord(PsiSearchHelperImpl.java:249)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:1129)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:755)
    at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:24)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
    at com.intellij.util.MergeQuery.processResults(MergeQuery.java:26)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
    at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:35)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:88)
    at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:30)
    at com.intellij.find.findUsages.FindUsagesHandlerBase.findReferencesToHighlight(FindUsagesHandlerBase.java:123)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getReferences(IdentifierHighlighterPass.java:302)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:272)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$2(IdentifierHighlighterPass.java:252)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:251)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:227)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
] 
2020-08-19 09:53:28,371 [52248490]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:53:28,373 [52248492]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,374 [52248493]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,387 [52248506]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:53:28,390 [52248509]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:53:28,391 [52248510]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,392 [52248511]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,406 [52248525]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:53:28,417 [52248536]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:53:28,419 [52248538]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,420 [52248539]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:28,437 [52248556]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:53:32,004 [52252123]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:53:32,005 [52252124]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:32,006 [52252125]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:32,016 [52252135]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:53:32,018 [52252137]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:53:32,019 [52252138]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:32,020 [52252139]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:32,033 [52252152]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.config.component.parser.ParameterServiceParser 
2020-08-19 09:53:33,523 [52253642]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:53:33,523 [52253642]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:33,524 [52253643]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:33,539 [52253658]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlTagParser 
2020-08-19 09:53:42,242 [52262361]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:53:42,243 [52262362]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,244 [52262363]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,258 [52262377]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:53:42,272 [52262391]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.doctrine.component.EntityNamesServiceParser 
2020-08-19 09:53:42,273 [52262392]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,273 [52262392]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,287 [52262406]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.doctrine.component.EntityNamesServiceParser 
2020-08-19 09:53:42,287 [52262406]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.doctrine.component.DocumentNamespacesParser 
2020-08-19 09:53:42,288 [52262407]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,289 [52262408]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:53:42,304 [52262423]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.doctrine.component.DocumentNamespacesParser 
2020-08-19 09:53:42,839 [52262958]   INFO -                 Symfony-Plugin - update routing: /xxxxxxxxxxxxxx/var/cache/dev/UrlGenerator.php 
2020-08-19 09:53:42,876 [52262995]   INFO -                 Symfony-Plugin - update routing: /xxxxxxxxxxxxxx/var/cache/dev/UrlMatcher.php 
2020-08-19 09:54:19,170 [52299289]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:54:19,171 [52299290]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:54:19,171 [52299290]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:54:19,199 [52299318]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPathServiceParser 
2020-08-19 09:54:21,081 [52301200]   INFO -                 Symfony-Plugin - new instance: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:54:21,083 [52301202]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:54:21,083 [52301202]   INFO -                         STDERR - [Fatal Error] :21:54: XML document structures must start and end within the same entity. 
2020-08-19 09:54:21,111 [52301230]   INFO -                 Symfony-Plugin - update: fr.adrienbrault.idea.symfony2plugin.dic.XmlServiceParser 
2020-08-19 09:54:21,135 [52301254]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
```
</p>
</details>

I hope it makes sense and that is something fixable, let me know if I can provide more details or help to solve this bug!

**Comment by norberttech** [comment]
hey @Haehnchen is there any chance you could look at this and at least let me know if anything is missing here to confirm/deny this as a bug? 
It keeps happening at least a few times per day and JetBrains blames plugin

**Comment by norberttech** [comment]
Turns out that JetBrains tech support was wrong and I was able to reproduce this issue even with Symfony Plugin disabled, now they blame different plugging (: 

Sorry for opening false incident
