### ISSUE TITLE
new update of 203.xxxx broken the plugin

### ISSUE THREAD

**Issue by ishu202** [Haehnchen/idea-php-symfony2-plugin#1563]
i just updated my php storm and it broke the plugin. its sad because i dont get the autocomplition anymore. its sad.

**Comment by danb1974** [comment]
Maybe related to a storm of errors, appearing in phpstom 2020.3

<pre>java.lang.Throwable: Duplicate type providers with key '': ControllerFieldTypeProvider,ViewHelperInViewTypeProvider,ViewHelperInViewHelperTypeProvider,ThisVariableInViewTypeProvider
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.jetbrains.php.PhpIndexImpl.getTypeProviders(PhpIndexImpl.java:242)
        at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:161)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:122)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:211)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:700)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:602)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:589)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.ObjectManagerFindContextTypeProvider.complete(ObjectManagerFindContextTypeProvider.java:89)
[snip]
</pre>

**Comment by praad** [comment]
java.lang.Throwable: Duplicate type providers with key '元': MockProphecyTypeProvider,MockProphecyTypeProvider
Duplicate type providers with key 'ᖉ': SetUpTypeProvider,SetUpTypeProvider
Duplicate type providers with key 'Ţ': ProphecyArgumentTypeProvider,ProphecyArgumentTypeProvider
Duplicate type providers with key 'ᔰ': ProphecyTypeProvider,ProphecyTypeProvider
Duplicate type providers with key 'ᔴ': GetMockTypeProvider,GetMockTypeProvider
Duplicate type providers with key 'ᔷ': RevealProphecyTypeProvider,RevealProphecyTypeProvider
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.jetbrains.php.PhpIndexImpl.getTypeProviders(PhpIndexImpl.java:242)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:161)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:122)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:101)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:632)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$resolveInHierarchy$0(MemberReferenceImpl.java:202)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveInHierarchy(MemberReferenceImpl.java:199)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:184)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobal(MethodReferenceImpl.java:93)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$static$0(PhpReferenceImpl.java:159)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:149)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:164)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:157)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:153)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:139)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getMultiResolvedMethod(PhpElementsUtil.java:1448)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher$StringParameterRecursiveMatcher.match(MethodMatcher.java:190)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher.getMatchedSignatureWithDepth(MethodMatcher.java:46)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodParameterReferenceContributor$1.getReferencesByElement(MethodParameterReferenceContributor.java:80)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:432)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:136)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:116)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:336)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:269)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:601)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:96)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by amine-y** [comment]
Same here

`java.lang.Throwable: Duplicate type providers with key '元': MockProphecyTypeProvider,MockProphecyTypeProvider
Duplicate type providers with key 'ᖉ': SetUpTypeProvider,SetUpTypeProvider
Duplicate type providers with key 'Ţ': ProphecyArgumentTypeProvider,ProphecyArgumentTypeProvider
Duplicate type providers with key 'ᔰ': ProphecyTypeProvider,ProphecyTypeProvider
Duplicate type providers with key 'ᔴ': GetMockTypeProvider,GetMockTypeProvider
Duplicate type providers with key 'ᔷ': RevealProphecyTypeProvider,RevealProphecyTypeProvider
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.jetbrains.php.PhpIndexImpl.getTypeProviders(PhpIndexImpl.java:242)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getTypeFromAST$1(PhpTypeInfo.java:79)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getTypeFromAST(PhpTypeInfo.java:74)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:57)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.PhpTypedElementImpl.getType(PhpTypedElementImpl.java:24)
	at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:631)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$resolveInHierarchy$0(MemberReferenceImpl.java:202)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveInHierarchy(MemberReferenceImpl.java:199)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:184)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobal(MethodReferenceImpl.java:93)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$static$0(PhpReferenceImpl.java:159)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:149)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:164)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:157)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:153)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1160)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1190)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1199)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher$AbstractMethodParameterMatcher.isCallTo(MethodMatcher.java:290)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher$StringParameterMatcher.match(MethodMatcher.java:123)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher.getMatchedSignatureWithDepth(MethodMatcher.java:37)
	at fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher.getMatchedSignatureWithDepth(MethodMatcher.java:25)
	at fr.adrienbrault.idea.symfony2plugin.config.SymfonyPhpReferenceContributor$1.getReferencesByElement(SymfonyPhpReferenceContributor.java:110)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:432)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitPhpStringLiteralExpression(PhpRefUtil.java:597)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:36)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.apply(PhpElementVisitor.java:30)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitElementsRecursive(PhpRefUtil.java:192)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitPhpFunctor(PhpRefUtil.java:515)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.processMemberReference(PhpRefUtil.java:500)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitMemberReference(PhpRefUtil.java:484)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitPhpMethodReference(PhpRefUtil.java:478)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:32)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.apply(PhpElementVisitor.java:30)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitElementsRecursive(PhpRefUtil.java:192)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil$1.visitPhpAssignmentExpression(PhpRefUtil.java:234)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefUtil.addReferencesTo(PhpRefUtil.java:183)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefElementImpl.buildInnerReference(PhpRefElementImpl.java:202)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitPhpExpression(PhpExpressionVisitor.java:120)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitPhpAssignmentExpression(PhpExpressionVisitor.java:138)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.apply(PhpElementVisitor.java:30)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitElements(PhpExpressionVisitor.java:287)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitPhpStatement(PhpExpressionVisitor.java:282)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:19)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.jetbrains.php.lang.psi.visitors.PhpElementVisitor.apply(PhpElementVisitor.java:30)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitElements(PhpExpressionVisitor.java:287)
	at com.jetbrains.php.lang.inspections.reference.visitors.PhpExpressionVisitor.visitPhpGroupStatement(PhpExpressionVisitor.java:105)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:22)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefElementImpl.buildReferencesInside(PhpRefElementImpl.java:194)
	at com.jetbrains.php.lang.inspections.reference.elements.PhpRefMethodImpl.buildReferences(PhpRefMethodImpl.java:176)
	at com.jetbrains.php.lang.inspections.reference.PhpRefManagerImpl$1.visitDeclaration(PhpRefManagerImpl.java:240)
	at com.jetbrains.php.lang.inspections.reference.PhpRefManagerImpl$1.visitPhpMethod(PhpRefManagerImpl.java:258)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:91)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.inspections.reference.PhpRefManagerImpl.visitElement(PhpRefManagerImpl.java:302)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:456)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:76)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:76)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:29)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:76)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:29)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
	at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitFile(RefManagerImpl.java:524)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:204)
	at com.intellij.analysis.AnalysisScope.doProcessFile(AnalysisScope.java:421)
	at com.intellij.analysis.AnalysisScope.lambda$processFile$7(AnalysisScope.java:368)
	at com.intellij.analysis.AnalysisScope.lambda$commitAndRunInSmartMode$8(AnalysisScope.java:384)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$8(PsiDocumentManagerBase.java:504)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$9(PsiDocumentManagerBase.java:529)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:527)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:504)
	at com.intellij.analysis.AnalysisScope.commitAndRunInSmartMode(AnalysisScope.java:382)
	at com.intellij.analysis.AnalysisScope.processFile(AnalysisScope.java:368)
	at com.intellij.analysis.AnalysisScope.lambda$acceptImpl$0(AnalysisScope.java:275)
	at com.intellij.analysis.AnalysisScope.lambda$accept$9(AnalysisScope.java:432)
	at com.intellij.openapi.vfs.VfsUtilCore$1.visitFileEx(VfsUtilCore.java:276)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:292)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:272)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:265)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:429)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:320)
	at com.intellij.analysis.AnalysisScope.acceptImpl(AnalysisScope.java:270)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:254)
	at com.intellij.codeInspection.reference.RefManagerImpl.findAllDeclarations(RefManagerImpl.java:337)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runGlobalTools(GlobalInspectionContextImpl.java:555)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:253)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:262)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:262)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:215)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by ishu202** [comment]
i solved the issue by downgrading php storm.
