### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException

### ISSUE THREAD

**Issue by AlexeyKosov** [Haehnchen/idea-php-symfony2-plugin#1597]
PhpStorm 2021.1 Beta
Build #PS-211.6693.25, built on March 25, 2021
Runtime version: 11.0.10+9-b1341.21 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: String Manipulation (8.13.203.000.0), com.hjf.redis.manager.redis-manager (1.2.0), de.espend.idea.laravel (0.15.4), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.22.206), ru.adelf.idea.dotenv (2021.1)

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create fr.adrienbrault.idea.symfony2plugin.Settings because container is already disposed: Project(name=sales v2.0, containerState=DISPOSE_COMPLETED, componentStore=\\wsl$\ayelect\home\ubuntu\domains\ayelect\sales) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:522)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:498)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by AlexeyKosov** [comment]
Occurred again 

PhpStorm 2021.1 RC
Build #PS-211.6693.78, built on April 1, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: String Manipulation (8.13.203.000.0), de.espend.idea.laravel (0.15.4), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.22.206), ru.adelf.idea.dotenv (2021.1)

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create fr.adrienbrault.idea.symfony2plugin.Settings because container is already disposed: Project(name=sales v2.0, containerState=DISPOSE_COMPLETED, componentStore=\\wsl$\ayelect\home\ubuntu\domains\ayelect\sales) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:522)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:498)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at fr.adrienbrault.idea.symfony2plugin.Settings.getInstance(Settings.java:98)
	at fr.adrienbrault.idea.symfony2plugin.dic.webDeployment.ServiceContainerRemoteFileStorage.files(ServiceContainerRemoteFileStorage.java:32)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.utils.RemoteWebServerUtil.hasConfiguredRemoteFile(RemoteWebServerUtil.java:116)
	at fr.adrienbrault.idea.symfony2plugin.webDeployment.WebDeploymentProjectComponent$MyTimerTask.run(WebDeploymentProjectComponent.java:61)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by ViPErCZ** [comment]
same on 2021.1.2
