### ISSUE TITLE
Unable to search in files

### ISSUE THREAD

**Issue by autistic456** [Haehnchen/idea-php-symfony2-plugin#1626]
java.lang.Throwable: unable to get stub builder for file with file = file:///home/patrik/Desktop/symfony_doctrine/vendor/doctrine/migrations/download-box.sh, file type = com.intellij.sh.ShFileType@2c48d264, indexed file type = com.intellij.sh.ShFileType@2c48d264, , stubBindingRoot = ShFile, languages = [Shell Script], fileTypes = [Shell Script], files = [ShFile], roots = []
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:115)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:66)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:284)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:330)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:92)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:80)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:565)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:981)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:956)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1031)
	at com.jetbrains.php.PhpIndexImpl.getTraitsByFQN(PhpIndexImpl.java:1060)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getTraits(PhpClassImpl.java:523)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.findMethodInTraits(PhpClassImpl.java:1095)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.findMethodsByName(PhpClassImpl.java:1014)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.findMethodByName(PhpClassImpl.java:970)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getParameterParametersInner(ServiceUtil.java:623)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.lambda$getParameterParameters$1(ServiceUtil.java:608)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at fr.adrienbrault.idea.symfony2plugin.util.dict.ServiceUtil.getParameterParameters(ServiceUtil.java:605)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ParameterCollector.getParameters(ContainerCollectionResolver.java:463)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ParameterCollector.resolve(ContainerCollectionResolver.java:401)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:229)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.convertClassNameToServices(ContainerCollectionResolver.java:314)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.findServiceDefinitionsLazy(ServiceIndexUtil.java:159)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.classNameMarker(ServiceLineMarkerProvider.java:109)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:76)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:181)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Haehnchen** [comment]
closed: wait for phpstorm 2021.1
