### ISSUE TITLE
java.lang.Throwable: Non-idempotent computation

### ISSUE THREAD

**Issue by wezniuc** [Haehnchen/idea-php-symfony2-plugin#1651]
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1c2d3d32 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@400bdcaf
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1c2d3d32] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@400bdcaf]

Recomputation gives com.intellij.util.CachedValueBase$Data@73e5d86c which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespacesInner(JsonFileIndexTwigNamespaces.java:55)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.lambda$getNamespaces$0(JsonFileIndexTwigNamespaces.java:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespaces(JsonFileIndexTwigNamespaces.java:42)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1343)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1269)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1257)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigFileMethodUsageOnIndex(TwigUtil.java:784)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.collectControllerTemplateVariables(TwigUtil.java:771)
	at fr.adrienbrault.idea.symfony2plugin.twig.variable.collector.ControllerVariableCollector.collectPsiVariables(ControllerVariableCollector.java:24)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:259)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.collectScopeVariables(TwigTypeResolveUtil.java:232)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.getRootVariableByName(TwigTypeResolveUtil.java:436)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigTypeResolveUtil.resolveTwigMethodName(TwigTypeResolveUtil.java:141)
	at fr.adrienbrault.idea.symfony2plugin.templating.inspection.TwigVariableDeprecatedInspection$MyPsiRecursiveElementVisitor.visit(TwigVariableDeprecatedInspection.java:56)
	at fr.adrienbrault.idea.symfony2plugin.templating.inspection.TwigVariableDeprecatedInspection$MyPsiRecursiveElementVisitor.visitElement(TwigVariableDeprecatedInspection.java:45)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by aeneid-19** [comment]
I'm getting this error a lot lately.
Plugin version: 0.23.209
PHPSTORM: 2021.1.2
OS: Linux Mint Debian 4
Need to check if it's also happening on Win 10.

**Comment by Haehnchen** [comment]
duplicate #1554
