### ISSUE TITLE
java.lang.AssertionError at com.jetbrains.php.lang.psi.resolve.types.PhpExcludeTypeTP.getBySignature

### ISSUE THREAD

**Issue by robme** [Haehnchen/idea-php-symfony2-plugin#1655]
I get this error every time I focus PhpStorm. It's been happening for some months now, since a PhpStorm update.

```
java.lang.AssertionError: #-#M#Ő#M#C\Drupal\Core\Entity\EntityInterface
	at com.jetbrains.php.lang.psi.resolve.types.PhpExcludeTypeTP.getBySignature(PhpExcludeTypeTP.java:63)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:774)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:654)
	at com.jetbrains.php.lang.psi.resolve.types.PhpArrayAccessTP.getBySignature(PhpArrayAccessTP.java:187)
	at com.jetbrains.php.lang.psi.resolve.types.PhpArrayAccessTP.getBySignature(PhpArrayAccessTP.java:176)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:774)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:654)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:167)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:113)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:229)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:755)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:654)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpTypeProviderUtil.getTypeSignature(PhpTypeProviderUtil.java:173)
	at fr.adrienbrault.idea.symfony2plugin.dic.SymfonyContainerTypeProvider.getBySignature(SymfonyContainerTypeProvider.java:72)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:774)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:654)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:167)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:113)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:229)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:755)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:654)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:167)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:113)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:92)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:662)
	at com.jetbrains.php.lang.psi.elements.PhpTypedElement.getGlobalType(PhpTypedElement.java:53)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpArrayUsedOnlyForWriteInspection.arrayAssignmentByValue(PhpArrayUsedOnlyForWriteInspection.java:131)
	at com.jetbrains.php.lang.inspections.controlFlow.PhpArrayUsedOnlyForWriteInspection$1.visitPhpAssignmentExpression(PhpArrayUsedOnlyForWriteInspection.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:35)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by thereIsMostDefinitelyNothinToSeeHere** [comment]
```
java.lang.AssertionError: #-#-#-#-#-#M#C\--REMOVED--
	at com.jetbrains.php.lang.psi.resolve.types.PhpExcludeTypeTP.getBySignature(PhpExcludeTypeTP.java:63)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:776)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:649)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.decodeExtendedClassesAndSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:113)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.getExtendedClassesToSubstitutedTemplates(PhpGenericsBaseExtendedWithGenericTypeProvider.java:89)
	at com.jetbrains.php.lang.psi.resolve.types.generics.PhpGenericsBaseExtendedWithGenericTypeProvider.complete(PhpGenericsBaseExtendedWithGenericTypeProvider.java:67)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:158)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:158)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:94)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:688)
	at com.jetbrains.php.lang.psi.resolve.types.PhpOptionalCompletionTP.complete(PhpOptionalCompletionTP.java:34)
	at com.jetbrains.php.PhpIndexImpl.lambda$doCompleteType$1(PhpIndexImpl.java:158)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:158)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:237)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:757)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpTypeProviderUtil.getResolvedParameter(PhpTypeProviderUtil.java:99)
	at fr.adrienbrault.idea.symfony2plugin.dic.SymfonyContainerTypeProvider.getBySignature(SymfonyContainerTypeProvider.java:83)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:776)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:171)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:115)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:237)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:757)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:662)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:649)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.getBySignature(PhpExceptionAnalysisService.java:371)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.collectThrownExceptions(PhpExceptionAnalysisService.java:304)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.lambda$getPreventingRecursion$4(PhpExceptionAnalysisService.java:271)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.getPreventingRecursion(PhpExceptionAnalysisService.java:268)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.lambda$getThrownExceptions$2(PhpExceptionAnalysisService.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.getThrownExceptions(PhpExceptionAnalysisService.java:236)
	at com.jetbrains.php.lang.inspections.exception.PhpExceptionAnalysisService.getThrownExceptions(PhpExceptionAnalysisService.java:223)
	at com.jetbrains.php.lang.inspections.PhpThrownExceptionsAnalyzer.getExceptionClasses(PhpThrownExceptionsAnalyzer.java:76)
	at com.jetbrains.php.lang.inspections.PhpThrownExceptionsAnalyzer.getExceptionClasses(PhpThrownExceptionsAnalyzer.java:66)
	at com.jetbrains.php.lang.inspections.phpdoc.PhpDocRedundantThrowsInspection$buildVisitor$1.getThrownExceptions(PhpDocRedundantThrowsInspection.kt:81)
	at com.jetbrains.php.lang.inspections.phpdoc.PhpDocRedundantThrowsInspection$buildVisitor$1.visitPhpFunction(PhpDocRedundantThrowsInspection.kt:46)
	at com.jetbrains.php.lang.inspections.phpdoc.PhpDocRedundantThrowsInspection$buildVisitor$1.visitPhpMethod(PhpDocRedundantThrowsInspection.kt:40)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:89)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:353)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:353)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
PhpStorm 2021.2.1
Build #PS-212.5080.71, built on August 26, 2021

Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-84-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: debugger.watches.in.variables=false, run.processes.with.pty=TRUE
Non-Bundled Plugins: com.alayouni.ansiHighlight (1.2.4), com.ultrahob.zerolength.plugin (0.93), Jetbrains TeamCity Plugin (2021.1.92869), com.intellij.ideolog (203.0.27.0), org.sonarlint.idea (5.2.0.35150), com.intellij.properties (212.4746.57), io.pivotal.jasmine (1.5), Karma (212.4746.57), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.211), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), NEON support (0.5.1)
Current Desktop: MATE

**Comment by thereIsMostDefinitelyNothinToSeeHere** [comment]
I had to disable the plugin, since I had this error on numerous files and was bombarded by an endless stream of errors.

**Comment by jhard** [comment]
I cannot reliably reproduce the issue, but I'm facing it as well. It happens when I have multiple projects opened and then open another one. For me, it always happens on one particular file which is part of a project that other projects include as a library path.

Restarting phpstorm works. I thought it might be related to shared indices, but disabling those has not solved it.

Anything useful we can do to debug the issue?
