### ISSUE TITLE
Exception in plugin Symfony Support (0.23.212)

### ISSUE THREAD

**Issue by ricardobruzual** [Haehnchen/idea-php-symfony2-plugin#1715]
PhpStorm v2021.2.2
Symfony Support v0.23.212

```java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@11526619 != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@57ebebaa
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@11526619, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2c302082, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1176683c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1396a6a5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1b28b9c6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3631ae11, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@14a40763, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@322128dc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6c1941d7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@57633b63, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@63c8a1f3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5894129e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7ea5e7a2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@30d36336, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@16b29be6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6eca6b4c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3f8319c0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@14e207d5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@168dd304, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2ba05a92, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@cca0b3f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@89279dc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@707f8e39, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@59223e6e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5ed5586, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1eaa907e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1228dbd4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5ab156b1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@359f6904, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7ffc36a9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2bdea4f9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7b8a7bed, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3513ead1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2b44dba4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@75634b59, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5d1e130b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77f12f1b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7a6543ba, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@15b3f62c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@381829da, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@466f4035, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1647a3d1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1c4f35a3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@65609909, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@59321378, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@72406aa4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@17c7ab62, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@760ed042, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3f6ea428, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4e0aec2b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@64bcd233, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@64308226, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2eb5356c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3747ef25, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@35689eb4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@55291b8d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@52b04a11, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5a06b9a5] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@57ebebaa, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2b6a016f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@360282fc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6632b6ef, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@916e01d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@720ce929, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50bb80f6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@23cdc1c0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1de5cbac, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@8353c98, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@405b158, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@490ba3d9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7a00b9ff, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5b708bdb, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@72567e9c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@66571e64, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@19678c10, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4696f2b4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@775d664, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@598f5cd0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7cad4cfd, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@ddf028e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@243023a7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7fa822d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@11a6ec8b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@64184743, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@41106d7c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@12287499, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@344c00e3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@12486b76, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50718fce, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1aca5e5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5533e62b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4f12420, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@58a2c48f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3cc5d1f3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@760d6afe, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7bd0803b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3598a572, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@27c0a07b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3a0764e7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@45a9fac4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@35ea6436, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@170bd988, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@16aaa7d2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1c5f1019, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7af20c70, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@337c5d3f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@702bf8b5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1410e171, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7e6bfe0f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2f2fd158, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6e6a58, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@13e6084d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@32dc17b8, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6328b5aa, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@10e73f3d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3360f90c]

Recomputation gives com.intellij.util.CachedValueBase$Data@6153490f which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:89)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:76)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespacesInner(JsonFileIndexTwigNamespaces.java:55)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.lambda$getNamespaces$0(JsonFileIndexTwigNamespaces.java:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at fr.adrienbrault.idea.symfony2plugin.templating.path.JsonFileIndexTwigNamespaces.getNamespaces(JsonFileIndexTwigNamespaces.java:42)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigNamespaces(TwigUtil.java:1366)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1292)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTemplateNamesForFile(TwigUtil.java:1280)
	at fr.adrienbrault.idea.symfony2plugin.templating.util.TwigUtil.getTwigFileMethodUsageOnIndex(TwigUtil.java:807)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.hasController(TwigIconProvider.java:57)
	at fr.adrienbrault.idea.symfony2plugin.twig.icon.TwigIconProvider.getIcon(TwigIconProvider.java:33)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:430)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)```

**Comment by patrickallaert** [comment]
Same version of PHPStorm and plugin. => same error/stacktrace.

**Comment by Haehnchen** [comment]
duplicate #1554
