### ISSUE TITLE
Outdated stub in index

### ISSUE THREAD

**Issue by n0-m4d** [Haehnchen/idea-php-symfony2-plugin#1722]
Outdated stub in index: file:///[...].php indexing timestamp = 1635247365276, binary = false, byte size = 1250, char size = 1250, doc=DocumentImpl[file:///[...].php], docSaved=true, wasIndexedAlready=true, queried at 1635247365276
doc length=0
file length=1250
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file doesn't exist; length = /[...].php

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:174)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:140)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:107)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:242)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:240)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:61)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:212)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:731)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:99)
	at com.intellij.psi.util.PsiTreeUtil.getChildOfType(PsiTreeUtil.java:344)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl.getStatements(PhpNamespaceImpl.java:48)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:40)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:44)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:44)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:44)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:755)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:716)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:173)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:77)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:185)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by oritlewski** [comment]
+1 I have the same error since I updated th "Symfony support" plugin today.
