### ISSUE TITLE
Symfony Support plugin crashes

### ISSUE THREAD

**Issue by ahmeier** [Haehnchen/idea-php-symfony2-plugin#1755]
I have recently noted that phpDoc blocks autogenerated by PhpStorm do no longer seem to accept the "use" declaration within a class definition. The whole path gets printed out. At the same time I have repeatedly received the plugin crash note listed below that seems to come from the symfony plugin.

I wonder whether the two are related. Here is the crash report:

Outdated stub in index: file:///pathDeletedForSecurityPurposes/AbstractController.php indexing timestamp = 1641099014571, binary = false, byte size = 4797, char size = 4818, doc=DocumentImpl[file:///pathDeletedForSecurityPurposesAbstractController.php], docSaved=true, wasIndexedAlready=true, queried at 1641099014571
doc length=4797
file length=4797
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
PSI length=4797
projects with file: 1
physical file exists; length = 4797

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:168)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:134)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:101)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:41)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:629)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:952)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:250)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:84)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1894)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:84)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:64)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$2(StubIndexImpl.java:284)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:330)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:92)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:80)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:565)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:981)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:956)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1031)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1068)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:622)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.isConvertibleFrom(PhpType.java:540)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isInstanceOf(PhpElementsUtil.java:466)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1186)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1204)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.isMethodReferenceInstanceOf(PhpElementsUtil.java:1213)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.MissingServiceInspection$MyPsiElementVisitor.visitElement(MissingServiceInspection.java:50)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:279)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:161)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:153)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:277)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:277)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Haehnchen** [comment]
not a plugin issue
