### ISSUE TITLE
Twig path autocomplete stopped working after plugin update.

### ISSUE THREAD

**Issue by berkut1** [Haehnchen/idea-php-symfony2-plugin#2040]
After the plugin was updated, twig path function show nothing. 
![path](https://user-images.githubusercontent.com/13355990/204940384-5ab0dc6d-62e0-4e60-b938-9d5fd028578e.png)
I tried `clear index` in symfony plugins but that didn't help.

There is also an error log
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at fr.adrienbrault.idea.symfony2plugin.routing.Route.getVariables(Route.java:90)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteLookupElement.formatTail(RouteLookupElement.java:62)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteLookupElement.renderElement(RouteLookupElement.java:48)
	at com.intellij.codeInsight.lookup.LookupElementPresentation.renderElement(LookupElementPresentation.java:223)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:273)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$addItemToLookup$4(CompletionProgressIndicator.java:457)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:202)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:663)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:201)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:456)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:446)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$2(CompletionThreading.java:162)
	at com.intellij.codeInsight.completion.BaseCompletionLookupArranger.batchUpdate(BaseCompletionLookupArranger.java:193)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.withSingleUpdate(CompletionProgressIndicator.java:368)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$3(CompletionThreading.java:160)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$flushBatchResult$4(CompletionThreading.java:159)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:113)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by berkut1** [comment]
Now it works. Thanks!
