### ISSUE TITLE
java.lang.Throwable: Too many element types registered

### ISSUE THREAD

**Issue by vitoff34** [Haehnchen/idea-php-symfony2-plugin#2277]
This error keeps coming up because of my Symfony Support.

I reinstalled PHPStorm and deleted all cache but still keeps popping up.

```
java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (11315) were registered for 'Language: ANY': NULL, WHITE_SPACE, BAD_CHARACTER, NEW_LINE_INDENT, ERROR_ELEMENT, CODE_FRAGMENT, DUMMY_HOLDER, VALID_STRING_ESCAPE_TOKEN, INVALID_CHARACTER_ESCAPE_TOKEN, INVALID_UNICODE_ESCAPE_TOKEN, FILE, KEYWORD_1, KEYWORD_2, KEYWORD_3, KEYWORD_4, STRING, SINGLE_QUOTED_STRING, NUMBER, IDENTIFIER, LINE_COMMENT, MU...

at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)

at com.intellij.psi.tree.IElementType.\<init\>(IElementType.java:115)

at com.intellij.psi.tree.IElementType.\<init\>(IElementType.java:92)

at com.intellij.psi.tree.ILazyParseableElementType.\<init\>(ILazyParseableElementType.java:29)

at com.intellij.psi.tree.ILazyParseableElementType.\<init\>(ILazyParseableElementType.java:25)

at com.jetbrains.php.dql.queryBuilder.DqlBuilderKt.parseDql$lambda$0(DqlBuilder.kt:100)

at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)

at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)

at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)

at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)

at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)

at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)

at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)

at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)

at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)

at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)

at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)

at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)

at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)

at com.jetbrains.php.dql.queryBuilder.DqlBuilderKt.parseDql(DqlBuilder.kt:93)

at com.jetbrains.php.dql.queryBuilder.DqlBuilderReferenceProvider.processQuery(DqlBuilderReferenceContributor.kt:58)

at com.jetbrains.php.dql.queryBuilder.DqlBuilderReferenceProvider.getReferencesByElement(DqlBuilderReferenceContributor.kt:52)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)

at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)

at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)

at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)

at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)

at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)

at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)

at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)

at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)

at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)

at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)

at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)

at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)

at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)

at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:35)

at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:490)

at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection.getTemplateNameIfMissing(PhpTemplateMissingInspection.java:85)

at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection.invoke(PhpTemplateMissingInspection.java:50)

at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection$1.visitElement(PhpTemplateMissingInspection.java:39)

at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)

at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:76)

at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:350)

at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)

at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:379)

at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)

at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)

at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:385)

at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:158)

at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:150)

at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:325)

at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)

at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)

at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:325)

at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:307)

at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)

at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)

at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)

at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)

at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)

at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:292)

at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:278)

at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)

at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```
Macbook Pro M3 Pro.

Symfony Support (2022.1.262)

**Comment by Haehnchen** [comment]
fixed already
