### ISSUE TITLE
NullPointerException: null keys not supported: null keys not supported

### ISSUE THREAD

**Issue by havvg** [Haehnchen/idea-php-symfony2-plugin#277]
As #238 has been closed, I'm opening a new issue. The error is now occurring like every two seconds.

```
08:01:54 NullPointerException: null keys not supported: null keys not supported
08:01:56 NullPointerException: null keys not supported: null keys not supported
08:01:58 NullPointerException: null keys not supported: null keys not supported
```

PHPStorm: 7.1.3 (133.982)
Plugin: 0.10.54 ("Check for updates" doesn't find a newer one)

```
null keys not supported: null keys not supported
java.lang.NullPointerException: null keys not supported
    at gnu.trove.THashMap.put(THashMap.java:162)
    at com.intellij.util.indexing.ValueContainerImpl.a(ValueContainerImpl.java:66)
    at com.intellij.util.indexing.ValueContainerImpl.addValue(ValueContainerImpl.java:55)
    at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:121)
    at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:66)
    at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:427)
    at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:398)
    at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:122)
    at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:110)
    at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:117)
    at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:77)
    at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:980)
    at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:955)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:930)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1001)
    at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:887)
    at fr.adrienbrault.idea.symfony2plugin.stubs.SymfonyProcessors$CollectProjectUniqueKeysStrong.getResult(SymfonyProcessors.java:78)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ParameterCollector.getParameters(ContainerCollectionResolver.java:324)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ParameterCollector.resolve(ContainerCollectionResolver.java:295)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ParameterCollector.access$100(ContainerCollectionResolver.java:260)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.convertIndexToService(ContainerCollectionResolver.java:188)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.getServices(ContainerCollectionResolver.java:162)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ContainerCollectionResolver$ServiceCollector.convertClassNameToServices(ContainerCollectionResolver.java:213)
    at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.findServiceDefinitions(ServiceIndexUtil.java:80)
    at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.classNameMarker(ServiceLineMarkerProvider.java:112)
    at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:58)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:77)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:64)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1150)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:368)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:194)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by matthbull** [comment]
getting this error again in PHPstorm 10

````
null keys not supported
java.lang.NullPointerException: null keys not supported
	at gnu.trove.THashMap.put(THashMap.java:161)
	at com.intellij.util.indexing.ValueContainerImpl.a(ValueContainerImpl.java:71)
	at com.intellij.util.indexing.ValueContainerImpl.addValue(ValueContainerImpl.java:62)
	at com.intellij.util.indexing.ChangeTrackingValueContainer$2.perform(ChangeTrackingValueContainer.java:159)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:152)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.size(ChangeTrackingValueContainer.java:76)
	at com.intellij.util.indexing.MemoryIndexStorage$1.process(MemoryIndexStorage.java:122)
	at com.intellij.util.indexing.MemoryIndexStorage.processKeys(MemoryIndexStorage.java:130)
	at com.intellij.util.indexing.MapReduceIndex.processAllKeys(MapReduceIndex.java:296)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:744)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:733)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches$3.compute(FileIndexCaches.java:109)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.getIndexKeysCache(FileIndexCaches.java:117)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.metadata.util.DoctrineMetadataUtil.getModels(DoctrineMetadataUtil.java:256)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:755)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:148)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:68)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```
