### ISSUE TITLE
[Error] New > Symfony2 > Xml service failed

### ISSUE THREAD

**Issue by shengjie** [Haehnchen/idea-php-symfony2-plugin#421]
when i try to create new Xml service file(New > Symfony2 > Xml service), an error occurred, and the file fails to create. (Yaml service file has no problem)
PHPStorm 8.0.2 #PS 139.732
Symfony2 plugin version 0.11.82

    Wrong line separators: '...n=\"1.0\" ?>\r\n\r\n<conta...' at offset 22
    java.lang.AssertionError: Wrong line separators: '...n=\"1.0\" ?>\r\n\r\n<conta...' at offset 22
        at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:66)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
        at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2407)
        at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:629)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:126)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:121)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:113)
        at com.intellij.psi.formatter.FormattingDocumentModelImpl.createOn(FormattingDocumentModelImpl.java:74)
        at com.intellij.lang.xml.XmlFormattingModelBuilder.createModel(XmlFormattingModelBuilder.java:43)
        at com.intellij.formatting.CoreFormatterUtil.buildModel(CoreFormatterUtil.java:48)
        at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:128)
        at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
        at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:102)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:89)
        at fr.adrienbrault.idea.symfony2plugin.action.ServiceActionUtil$1.run(ServiceActionUtil.java:89)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
        at fr.adrienbrault.idea.symfony2plugin.action.ServiceActionUtil.buildFile(ServiceActionUtil.java:86)
        at fr.adrienbrault.idea.symfony2plugin.action.NewXmlServiceAction.actionPerformed(NewXmlServiceAction.java:17)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
        at java.awt.Component.processMouseEvent(Component.java:6414)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
        at java.awt.Component.processEvent(Component.java:6179)
        at java.awt.Container.processEvent(Container.java:2084)
        at java.awt.Component.dispatchEventImpl(Component.java:4776)
        at java.awt.Container.dispatchEventImpl(Container.java:2142)
        at java.awt.Component.dispatchEvent(Component.java:4604)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
        at java.awt.Container.dispatchEventImpl(Container.java:2128)
        at java.awt.Window.dispatchEventImpl(Window.java:2492)
        at java.awt.Component.dispatchEvent(Component.java:4604)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
        at java.awt.EventQueue.access$400(EventQueue.java:82)
        at java.awt.EventQueue$2.run(EventQueue.java:676)
        at java.awt.EventQueue$2.run(EventQueue.java:674)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:690)
        at java.awt.EventQueue$3.run(EventQueue.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
    Caused by: java.lang.Throwable
        ... 62 more

**Comment by s3than** [comment]
When creating yml file

```
Wrong line separators: '...arameters:\r\n#    tem...' at offset 11
java.lang.AssertionError: Wrong line separators: '...arameters:\r\n#    tem...' at offset 11
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:66)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2407)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:629)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:561)
	at com.intellij.openapi.editor.impl.DocumentImpl.access$400(DocumentImpl.java:57)
	at com.intellij.openapi.editor.impl.DocumentImpl$7.run(DocumentImpl.java:985)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:992)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:462)
	at fr.adrienbrault.idea.symfony2plugin.action.ServiceActionUtil$1.run(ServiceActionUtil.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at fr.adrienbrault.idea.symfony2plugin.action.ServiceActionUtil.buildFile(ServiceActionUtil.java:86)
	at fr.adrienbrault.idea.symfony2plugin.action.NewYamlServiceAction.actionPerformed(NewYamlServiceAction.java:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.Throwable
	... 59 more
```
