### ISSUE TITLE
Additional xml container files throws exception

### ISSUE THREAD

**Issue by Tschebel** [Haehnchen/idea-php-symfony2-plugin#451]
Adding additional xml container files throws an exception. It worked before but i didn't notice when it stopped. I guess it broke with the PHPStorm upgrade.
PHPStorm Version: 8.0.3 - Build: 139.1348
Plugin Version: 0.11.86 (tried with 0.11.85 too, same issue)
Type of project: Custom with standalone Service Container Component
EAP Channel: No
Trace:

```
Argument for @NotNull parameter 'ancestor' of com/intellij/openapi/vfs/VfsUtilCore.getRelativePath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'ancestor' of com/intellij/openapi/vfs/VfsUtilCore.getRelativePath must not be null
	at com.intellij.openapi.vfs.VfsUtilCore.getRelativePath(VfsUtilCore.java)
	at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm.getPathDialog(ContainerSettingsForm.java:231)
	at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm.access$400(ContainerSettingsForm.java:32)
	at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm$5.run(ContainerSettingsForm.java:130)
	at fr.adrienbrault.idea.symfony2plugin.ui.ContainerSettingsForm$5.run(ContainerSettingsForm.java:127)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:433)
	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:68)
	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:234)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:312)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:464)
	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1569)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1536)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:112)
	at com.intellij.ide.actions.TemplateProjectPropertiesAction.actionPerformed(TemplateProjectPropertiesAction.java:28)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:291)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:178)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:372)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:340)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by Tschebel** [comment]
it works again but i didn't manage to find out why. I didn't change project/settings or cleared the cache.
PHPStorm and Plugin Versions are still the same.
