### ISSUE TITLE
[Routing/Index] Exception when open a xml routing file

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#592]
```
com.intellij.lang.javascript.psi.impl.JSVarStatementImpl cannot be cast to com.jetbrains.php.lang.psi.elements.PhpNamespace
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSVarStatementImpl cannot be cast to com.jetbrains.php.lang.psi.elements.PhpNamespace
    at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil$1.process(PhpIndexUtil.java:39)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:186)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:54)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:274)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:265)
    at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:265)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:238)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
    at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:39)
    at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
    at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getActionMethods(ControllerIndex.java:95)
    at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getActions(ControllerIndex.java:39)
    at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getControllerAction(ControllerIndex.java:71)
    at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.resolveShortcutName(ControllerIndex.java:166)
    at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getControllerMethod(ControllerIndex.java:200)
    at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getMethodsOnControllerShortcut(RouteHelper.java:174)
    at fr.adrienbrault.idea.symfony2plugin.routing.XmlLineMarkerProvider.attachRouteActions(XmlLineMarkerProvider.java:50)
    at fr.adrienbrault.idea.symfony2plugin.routing.XmlLineMarkerProvider.collectSlowLineMarkers(XmlLineMarkerProvider.java:32)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by martinjeannot** [comment]
Happens also on yaml routing file
```
java.lang.ClassCastException: com.intellij.lang.javascript.psi.impl.JSVarStatementImpl cannot be cast to com.jetbrains.php.lang.psi.elements.PhpNamespace
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil$1.process(PhpIndexUtil.java:39)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:186)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:54)
	at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:274)
	at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:265)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:265)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:238)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:39)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
	at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getActionMethods(ControllerIndex.java:95)
	at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getActions(ControllerIndex.java:39)
	at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getControllerAction(ControllerIndex.java:71)
	at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.resolveShortcutName(ControllerIndex.java:166)
	at fr.adrienbrault.idea.symfony2plugin.util.controller.ControllerIndex.getControllerMethod(ControllerIndex.java:200)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getMethodsOnControllerShortcut(RouteHelper.java:174)
	at fr.adrienbrault.idea.symfony2plugin.routing.YamlLineMarkerProvider.attachRouteActions(YamlLineMarkerProvider.java:96)
	at fr.adrienbrault.idea.symfony2plugin.routing.YamlLineMarkerProvider.collectSlowLineMarkers(YamlLineMarkerProvider.java:37)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```
Using PhpStorm 9.0.2, Java 1.7 (on OpenJDK 64bit)

**Comment by Haehnchen** [comment]
already fixed by index improvements
