### ISSUE TITLE
AssertionError after upgrade to EAP-143-129 (file=PHP file; tree=Element(FILE))

### ISSUE THREAD

**Issue by rehoehle** [Haehnchen/idea-php-symfony2-plugin#596]
02:03:02 AssertionError
         file=PHP file; tree=Element(FILE)
         each of class class com.jetbrains.php.lang.psi.elements.impl.MethodImpl; valid=true; node=null; stub=PhpMethodStubImpl
         each of class class com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl; valid=true; node=null; stub=PhpClassStubImpl{Bundle}
         each of class class com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl; valid=true; node=null; stub=PhpNamespaceStubImpl
         each of class class com.jetbrains.php.lang.psi.PhpFileImpl; valid=true; same file=true; current tree= Element(FILE); stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}528424289; physical=true
         each stub PhpMethodStubImpl
         each stub PhpClassStubImpl{Bundle}
         each stub PhpNamespaceStubImpl
         each stub PsiFileStubImplPsiFileStubImpl{myFile=PHP file, myInvalidationReason=null, myStubRoots=[Lcom.intellij.psi.stubs.PsiFileStub;@5261db6e, stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}... (show balloon)

Every click i get that exception its a bit annoying.

**Comment by rehoehle** [comment]
Ok i don't know if its the solution but i've invalidate my cache and the error doesn't seem to appear again. Perhaps someone can validate that error?

**Comment by Geolim4** [comment]
I got the bug too. Plus, it's blocking a cannot open files anymore.

**Comment by Haehnchen** [comment]
just updated one project to 143.129. not getting this issue. can you provide a full stacktrace?

**Comment by rehoehle** [comment]
If i have that error the next time i try to post a complete stack.

**Comment by shyim** [comment]
Here the full stacktrace :)

```javascript
file=PHP file; tree=Element(FILE)
 each of class class com.jetbrains.php.lang.psi.elements.impl.MethodImpl; valid=true; node=null; stub=PhpMethodStubImpl
 each of class class com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl; valid=true; node=null; stub=PhpClassStubImpl{CodaFrameApplication}
 each of class class com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl; valid=true; node=null; stub=PhpNamespaceStubImpl
 each of class class com.jetbrains.php.lang.psi.PhpFileImpl; valid=true; same file=true; current tree= Element(FILE); stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}1917418; physical=true
 each stub PhpMethodStubImpl
 each stub PhpClassStubImpl{CodaFrameApplication}
 each stub PhpNamespaceStubImpl
 each stub PsiFileStubImplPsiFileStubImpl{myFile=PHP file, myInvalidationReason=null, myStubRoots=[Lcom.intellij.psi.stubs.PsiFileStub;@1b0acf2, stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}1917418, lastStubTreeHash=null}
java.lang.AssertionError: file=PHP file; tree=Element(FILE)
 each of class class com.jetbrains.php.lang.psi.elements.impl.MethodImpl; valid=true; node=null; stub=PhpMethodStubImpl
 each of class class com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl; valid=true; node=null; stub=PhpClassStubImpl{CodaFrameApplication}
 each of class class com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl; valid=true; node=null; stub=PhpNamespaceStubImpl
 each of class class com.jetbrains.php.lang.psi.PhpFileImpl; valid=true; same file=true; current tree= Element(FILE); stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}1917418; physical=true
 each stub PhpMethodStubImpl
 each stub PhpClassStubImpl{CodaFrameApplication}
 each stub PhpNamespaceStubImpl
 each stub PsiFileStubImplPsiFileStubImpl{myFile=PHP file, myInvalidationReason=null, myStubRoots=[Lcom.intellij.psi.stubs.PsiFileStub;@1b0acf2, stubTree=StubTree{myDebugInfo='created in getStubTree(); with backReference', myRoot=PsiFileStubImpl}1917418, lastStubTreeHash=null}
	at com.intellij.extapi.psi.StubBasedPsiElementBase.b(StubBasedPsiElementBase.java:183)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:104)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:95)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:67)
	at com.jetbrains.php.codeInsight.controlFlow.PhpControlFlowBuilder.build(PhpControlFlowBuilder.java:105)
	at com.jetbrains.php.codeInsight.PhpScopeImpl.getControlFlow(PhpScopeImpl.java:30)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.getControlFlow(FunctionImpl.java:246)
	at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.checkContainsFunction(PhpMethodParametersCountMismatchInspection.java:79)
	at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.inspect(PhpMethodParametersCountMismatchInspection.java:50)
	at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.visitPhpMethodReference(PhpMethodParametersCountMismatchInspection.java:94)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:30)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by ndench** [comment]
I'm getting the same error, normally more than 50 times a day.

**Comment by dariuszz123** [comment]
Can confirm exact same issue with 143.129

**Comment by Haehnchen** [comment]
can someone validate it also on 143.279 ? ;)

**Comment by shyim** [comment]
It is fixed with the latest eap
@see https://ea.jetbrains.com/browser/ea_reports/963438

**Comment by Geolim4** [comment]
@shyim It's a private link :)
Buti confirm that it's fixed with the latest EAP update.

**Comment by rehoehle** [comment]
Thx its working =)
