### ISSUE TITLE
Argument for @NotNull parameter 'className'

### ISSUE THREAD

**Issue by oleg-andreyev** [Haehnchen/idea-php-symfony2-plugin#609]
phpStorm 10 EAP, Build#: PS 143.434
```
Argument for @NotNull parameter 'className' of fr/adrienbrault/idea/symfony2plugin/util/PhpElementsUtil.getClassInsideNamespaceScope must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'className' of fr/adrienbrault/idea/symfony2plugin/util/PhpElementsUtil.getClassInsideNamespaceScope must not be null
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getClassInsideNamespaceScope(PhpElementsUtil.java)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.metadata.util.DoctrineMetadataUtil$3.compute(DoctrineMetadataUtil.java:127)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.metadata.util.DoctrineMetadataUtil.findMetadataForRepositoryClass(DoctrineMetadataUtil.java:146)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.metadata.util.DoctrineMetadataUtil.findMetadataForRepositoryClass(DoctrineMetadataUtil.java:110)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.repositoryClassMarker(ServiceLineMarkerProvider.java:175)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:66)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```
#425

**Comment by King2500** [comment]
Same here.
