### ISSUE TITLE
null keys not supported

### ISSUE THREAD

**Issue by oleg-andreyev** [Haehnchen/idea-php-symfony2-plugin#615]
PS10, Build#143.381

```
null keys not supported
java.lang.NullPointerException: null keys not supported
	at gnu.trove.THashMap.put(THashMap.java:161)
	at com.intellij.util.indexing.ValueContainerImpl.a(ValueContainerImpl.java:71)
	at com.intellij.util.indexing.ValueContainerImpl.addValue(ValueContainerImpl.java:62)
	at com.intellij.util.indexing.ChangeTrackingValueContainer$2.perform(ChangeTrackingValueContainer.java:159)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:152)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.size(ChangeTrackingValueContainer.java:76)
	at com.intellij.util.indexing.MemoryIndexStorage$1.process(MemoryIndexStorage.java:122)
	at com.intellij.util.indexing.MemoryIndexStorage.processKeys(MemoryIndexStorage.java:130)
	at com.intellij.util.indexing.MapReduceIndex.processAllKeys(MapReduceIndex.java:296)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:744)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:733)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches$3.compute(FileIndexCaches.java:109)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.stubs.cache.FileIndexCaches.getIndexKeysCache(FileIndexCaches.java:117)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.metadata.util.DoctrineMetadataUtil.getModels(DoctrineMetadataUtil.java:253)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:755)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:142)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:65)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by Haehnchen** [comment]
fixed ;)
