### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by dspiegel** [Haehnchen/idea-php-symfony2-plugin#617]
Getting repeated errors from IDE start until IDE crashes, following latest update:
Assertion failed: unable to get stub builder for com.jetbrains.twig.TwigFileType@2c6555b1

Plugin Version 0.11.101
PhpStorm Version: PhpStorm-143.381.48
Symfony 2.7

```
Assertion failed: unable to get stub builder for com.jetbrains.twig.TwigFileType@2c6555b1
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:79)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:231)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:582)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:570)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:252)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:212)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:77)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:39)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:789)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:754)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:143)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:66)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by Haehnchen** [comment]
looking for some previous phpstorm eap issues to me. do you have other environments to test?

**Comment by dspiegel** [comment]
@Haehnchen Continue to get these errors. 
Currently running Latest PhpStorm 10.0.2 and Symfony 2 plugin 0.11.107
IDE wants me to disable Symfony 2 plugin due to errors.

```
Assertion failed: unable to get stub builder for com.jetbrains.rest.RestFileType@6cdb5204
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:79)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:231)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:582)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:570)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:252)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:212)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:77)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:39)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:789)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:754)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:151)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:69)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by dspiegel** [comment]
Still happening. Only using Symfony 2 not 3.
PHPStorm 10.0.3 
Symfony 2.3 - 2.8
Plugin Version: 0.11.107

**Got 54 errors while I was writing this post!**

**Is there at least a work around for this, other than disabling this plugin?**

```
Assertion failed: unable to get stub builder for com.jetbrains.twig.TwigFileType@76f82622
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:79)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:231)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:582)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:570)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:252)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:212)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:77)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:39)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpIndexUtil.getPhpClassInsideNamespace(PhpIndexUtil.java:27)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:789)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getModelClasses(EntityHelper.java:754)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.entityClassMarker(ServiceLineMarkerProvider.java:151)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:69)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by dspiegel** [comment]
@Haehnchen 
I have not seen any more errors since Plugin version 0.11.108 .

Thanks
