### ISSUE TITLE
Do not call synchronous refresh under read lock

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#646]
PS 143.1184, Plugin 0.11.104. I don't know what steps to do fo reproducing this issue, just noticed it in error log.

```
Do not call synchronous refresh under read lock (except from EDT) - this will cause a deadlock if there are any events to fire.
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:62)
    at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:120)
    at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processSingleEvent(RefreshQueueImpl.java:143)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:254)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.a(VirtualDirectoryImpl.java:96)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:261)
    at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:136)
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:73)
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByIoFile(LocalFileSystemBase.java:230)
    at com.intellij.openapi.vfs.VfsUtil.findFileByIoFile(VfsUtil.java:232)
    at fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath.getDirectory(TwigPath.java:110)
    at fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath.getRelativePath(TwigPath.java:70)
    at fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath.getDirectory(TwigPath.java:80)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper.getTemplateMapProxy(TwigHelper.java:158)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper.access$000(TwigHelper.java:53)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper$MyTwigOnlyTemplateFileMapCachedValueProvider.compute(TwigHelper.java:1695)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper.getTemplateMap(TwigHelper.java:94)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper.getTemplateFilesByName(TwigHelper.java:76)
    at fr.adrienbrault.idea.symfony2plugin.TwigHelper.getTwigFilesByName(TwigHelper.java:180)
    at fr.adrienbrault.idea.symfony2plugin.navigation.TemplateFileContributor.getNames(TemplateFileContributor.java:20)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
    at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by wheelsandcogs** [comment]
I'm getting this a lot as well.

**Comment by Koc** [comment]
looks like fixed
