### ISSUE TITLE
IllegalArgumentException on Indexing

### ISSUE THREAD

**Issue by distantbit** [Haehnchen/idea-php-symfony2-plugin#650]
I get an error when i load my Symfony Controller Files. It marks some lines yellow but there aren't any errors or deprecations. The PHPStorm log says:
`IllegalArgumentException: Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null`

**Comment by Haehnchen** [comment]
>Error after last update: Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
>Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
>java.lang.IllegalArgumentException: Ar gument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
>at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClassOnParameter(FormUtil.java)
at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClass(FormUtil.java:146)

**Comment by stanislav-sulima** [comment]
I have the same problem

PhpStorm 10.0.2, Build #PS-143.1184. Plugin version 0.11.105

```
Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClassOnParameter(FormUtil.java)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClass(FormUtil.java:146)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.resolveFormGetterCall(FormUtil.java:129)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.resolveFormGetterCallMethod(FormUtil.java:155)
	at fr.adrienbrault.idea.symfony2plugin.form.FormTypeReferenceContributor$5.getReferencesByElement(FormTypeReferenceContributor.java:261)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:66)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:60)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:283)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by stof** [comment]
I'm getting the same error:

```
Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'psiElement' of fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.getFormTypeClassOnParameter must not be null
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClassOnParameter(FormUtil.java)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.getFormTypeClass(FormUtil.java:146)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.resolveFormGetterCall(FormUtil.java:129)
	at fr.adrienbrault.idea.symfony2plugin.form.util.FormUtil.resolveFormGetterCallMethod(FormUtil.java:155)
	at fr.adrienbrault.idea.symfony2plugin.form.FormTypeReferenceContributor$5.getReferencesByElement(FormTypeReferenceContributor.java:261)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:66)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:60)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:283)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:38)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```
