### ISSUE TITLE
java.lang.NoClassDefFoundError: com/jetbrains/twig/TwigFile

### ISSUE THREAD

**Issue by MECU** [Haehnchen/idea-php-symfony2-plugin#658]
I get this error multiple times per day. It doesn't bother me, interrupt my work or otherwise cause any issues. I'm just getting tired of the red blinking error message. Occurs in plugin `Symfony2 - Clickable Views`

* What version of PHPStorm are you using ? 10.0.1
* What version of the plugin are you using ? 0.1.4
* What kind of project have you encountered the issue with ? Symfony2 full stack

Error Message: com/jetbrains/twig/TwigFile

````
com/jetbrains/twig/TwigFile
java.lang.NoClassDefFoundError: com/jetbrains/twig/TwigFile
	at com.xenji.php.symfony2.clickableviews.TwigViewPsiReference.isReferenceTo(TwigViewPsiReference.java:155)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$14.execute(PsiSearchHelperImpl.java:739)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:129)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:211)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:205)
	at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl$2.run(JobLauncherImpl.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.JobLauncherImpl.a(JobLauncherImpl.java:158)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:96)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:186)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.b(PsiSearchHelperImpl.java:914)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:598)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:174)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:139)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:171)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.twig.TwigFile PluginClassLoader[Symfony2 - Clickable Views, 0.1.4]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more
````

**Comment by Haehnchen** [comment]
just uninstall `com.xenji.php.symfony2.clickableviews` you are using the wrong plugin. :)

**Comment by MECU** [comment]
Well that was easy. Is there a way to remove it from the Jetbrains Plugin Repo so it can't be installed and cause problems anymore?

![image](https://cloud.githubusercontent.com/assets/4950394/11982109/a63483f6-a965-11e5-8ded-08ee0096dd82.png)

**Comment by Haehnchen** [comment]
removal request: https://github.com/xenji/phpstorm-symfony2-plugin/issues/20
