### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLArray - PHPStorm 11 EAP with Symfony 2 project

### ISSUE THREAD

**Issue by ivodvb** [Haehnchen/idea-php-symfony2-plugin#672]
My services cannot be found when I cmd + click on $container->get('my.service_name'). An exception occurs.

OS: `OSX El Capitan`
PHPStorm Version: `PHPStorm 11 EAP - PS-144.3168 built on January 20th 2016`
Plugin version: `0.11.108`
Project: `Symfony 2`
Error: `NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLArray`
Stack trace:

```org/jetbrains/yaml/psi/YAMLArray
java.lang.NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLArray
	at fr.adrienbrault.idea.symfony2plugin.config.yaml.YamlAnnotator.annotateConstructorArguments(YamlAnnotator.java:178)
	at fr.adrienbrault.idea.symfony2plugin.config.yaml.YamlAnnotator.annotate(YamlAnnotator.java:52)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)```

**Comment by gharlan** [comment]
same here

**Comment by Haehnchen** [comment]
it finally happens #626, #665 :(

**Comment by HollyIT** [comment]
I can confirm this myself. As I work on a YAML file, my error log quickly fills up with:

> NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLArray

Even a quick edit can lead to a couple dozen of these popping up.

**Comment by Haehnchen** [comment]
duplicate by #626; nightly build out
