### ISSUE TITLE
No class found definition error since 0.11.112

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-symfony2-plugin#688]
After #686 I've upgraded and I continually get the following error in the event log:
```
NoClassDefFoundError: org/apache/commons/vfs2/FileSystemException
```

Full stack trace:
```
org/apache/commons/vfs2/FileSystemException
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/FileSystemException
	at fr.adrienbrault.idea.symfony2plugin.Symfony2ProjectComponent.projectClosed(Symfony2ProjectComponent.java:104)
	at com.intellij.openapi.project.impl.ProjectImpl.a(ProjectImpl.java:412)
	at com.intellij.openapi.project.impl.ProjectImpl.access$300(ProjectImpl.java:63)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectClosed(ProjectImpl.java:440)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectClosed(ProjectManagerImpl.java:106)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:736)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$700(ProjectManagerImpl.java:67)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$10.run(ProjectManagerImpl.java:634)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:629)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:656)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:87)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$5$1.run(IdeFrameImpl.java:267)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.FileSystemException PluginClassLoader[fr.adrienbrault.idea.symfony2plugin, 0.11.112]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 32 more
```

**Comment by sidz** [comment]
same problem, and I can't open twig templates.

**Comment by Ezaki113** [comment]
@hoshsadiq @sidz try to invalidate cache with restart + reenable plugin for project. 
its helped me

**Comment by sidz** [comment]
@Ezaki113 PhpStorm 145.184.39 your solution doesn't help :(

**Comment by samimussbach** [comment]
I deleted the jar in the pluginfolder (~/.WebIde100/config/plugins/symfony2-plugin.jar or USER\.WebIde100\config\plugins\symfony2-plugin.jar on Win) and replaced it with the last stable Version 0.11.110 from https://plugins.jetbrains.com/plugin/download?pr=&updateId=24192
until the next Version is stable.

**Comment by Haehnchen** [comment]
for now just enable the plugin "Remote Hosts Access" for this missing class. cleanup follows

**Comment by samimussbach** [comment]
0.11.113 works for me, no errors any more
