### ISSUE TITLE
NPE exception in RouteHelper

### ISSUE THREAD

**Issue by scaytrase** [Haehnchen/idea-php-symfony2-plugin#750]
```
null
java.lang.NullPointerException
	at fr.adrienbrault.idea.symfony2plugin.routing.Route.<init>(Route.java:40)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.convertRouteConfig(RouteHelper.java:494)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.collectRoutesOnArrayCreation(RouteHelper.java:456)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getRoutesInsideUrlGeneratorFile(RouteHelper.java:426)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getRoutesInsideUrlGeneratorFile(RouteHelper.java:348)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getCompiledRoutes(RouteHelper.java:312)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getAllRoutesProxy(RouteHelper.java:978)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.access$000(RouteHelper.java:64)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper$3.compute(RouteHelper.java:965)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper.getAllRoutes(RouteHelper.java:971)
	at fr.adrienbrault.idea.symfony2plugin.navigation.PhpFoldingBuilder.attachRouteShortcuts(PhpFoldingBuilder.java:82)
	at fr.adrienbrault.idea.symfony2plugin.navigation.PhpFoldingBuilder.buildFoldRegions(PhpFoldingBuilder.java:65)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:60)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:257)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:243)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:119)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.access$000(FoldingUpdate.java:55)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:107)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:102)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:101)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:345)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:327)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

Spams the whole log. I'm writing a litle application based on SF 3.1 with custom dir layout (configured properly in plugin settings)

**Comment by scaytrase** [comment]
Thanks for the fast release!
