### ISSUE TITLE
Throwable: Empty PSI elements should not be passed to createDescriptor. 

### ISSUE THREAD

**Issue by MrMitch** [Haehnchen/idea-php-symfony2-plugin#788]
Hi,

I got an exception with the following message : 
**Empty PSI elements should not be passed to createDescriptor. Start: PsiErrorElement:Expected: right single quote or right double quote, end: PsiErrorElement:Expected: right single quote or right double quote, startContainingFile: PHP file**.

Full stack-trace bellow (click to expand).
<details>
```
Empty PSI elements should not be passed to createDescriptor. Start: PsiErrorElement:Expected: right single quote or right double quote, end: PsiErrorElement:Expected: right single quote or right double quote, startContainingFile: PHP file
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:70)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:75)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:64)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:66)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:97)
	at com.intellij.psi.PsiElementVisitor.visitErrorElement(PsiElementVisitor.java:46)
	at com.intellij.psi.impl.source.tree.PsiErrorElementImpl.accept(PsiErrorElementImpl.java:40)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:32)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.AssignmentExpressionImpl.accept(AssignmentExpressionImpl.java:39)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:89)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.accept(PhpClassImpl.java:517)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl.accept(PhpNamespaceImpl.java:92)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:101)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:28)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:845)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection.phpVisitor(CaseSensitivityServiceInspection.java:90)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection.access$000(CaseSensitivityServiceInspection.java:29)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$1.visitFile(CaseSensitivityServiceInspection.java:44)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:163)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
</details>

**Comment by MrMitch** [comment]
Hi, I saw you added the `fixed` label to this issue, should we close ?

**Comment by Haehnchen** [comment]
yes closes ;)
