### ISSUE TITLE
Empty PSI elements should not be passed to createDescriptor.

### ISSUE THREAD

**Issue by alsii** [Haehnchen/idea-php-symfony2-plugin#799]
Start: PsiErrorElement:Expected: right single quote or right double quote, end: PsiErrorElement:Expected: right single quote or right double quote, startContainingFile: PHP file

```
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:70)
    at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:75)
    at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:64)
    at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:66)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:102)
    at com.intellij.psi.PsiElementVisitor.visitErrorElement(PsiElementVisitor.java:46)
    at com.intellij.psi.impl.source.tree.PsiErrorElementImpl.accept(PsiErrorElementImpl.java:40)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:32)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.ArrayHashElementImpl.accept(ArrayHashElementImpl.java:27)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.ArrayCreationExpressionImpl.accept(ArrayCreationExpressionImpl.java:27)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:32)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReturnImpl.accept(PhpReturnImpl.java:21)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
    at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
    at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:89)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
    at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.accept(PhpClassImpl.java:517)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
    at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl.accept(PhpNamespaceImpl.java:92)
    at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
    at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$3.visitElement(CaseSensitivityServiceInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:28)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:845)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection.phpVisitor(CaseSensitivityServiceInspection.java:89)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection.access$000(CaseSensitivityServiceInspection.java:28)
    at fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection$1.visitFile(CaseSensitivityServiceInspection.java:43)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:163)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:310)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
    at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
    at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
    at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
    at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
    at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:60)
    at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:321)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:229)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by alsii** [comment]
Plugin version: 0.12.127
PhpStorm version: 2016.2.1
Build #PS-162.1889.1, built on August 23, 2016
JRE: 1.8.0_102-8u102-b14.1-1~bpo8+1-b14 i386
JVM: OpenJDK Server VM by Oracle Corporation

**Comment by MrMitch** [comment]
Got this today as well : 

```
java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: PsiErrorElement:Expected: right single quote or right double quote, end: PsiErrorElement:Expected: right single quote or right double quote, startContainingFile: PHP file
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:61)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:83)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:72)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:66)
	at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection.invoke(PhpTemplateMissingInspection.java:46)
	at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection.access$000(PhpTemplateMissingInspection.java:23)
	at fr.adrienbrault.idea.symfony2plugin.templating.PhpTemplateMissingInspection$1.visitElement(PhpTemplateMissingInspection.java:34)
	at com.intellij.psi.PsiElementVisitor.visitErrorElement(PsiElementVisitor.java:46)
	at com.intellij.psi.impl.source.tree.PsiErrorElementImpl.accept(PsiErrorElementImpl.java:40)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:276)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:244)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Plugin version: 0.16.167
PhpStorm version: 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic

**Comment by cedricziel** [comment]
From reading the code, this *might* happen when you're dealing with an empty string, or the document was otherwise tangled with.

I've proposed a simple fix with #1242. That might do the job

**Comment by Mohmdthabet** [comment]
Same Issue: 

java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: PsiErrorElement:Expected: right single quote or right double quote, end: PsiErrorElement:Expected: right single quote or right double quote, startContainingFile: PHP file
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:64)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:72)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:60)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:52)
	at fr.adrienbrault.idea.symfony2plugin.dic.inspection.MissingServiceInspection$MyPsiElementVisitor.visitElement(MissingServiceInspection.java:54)
	at com.intellij.psi.PsiElementVisitor.visitErrorElement(PsiElementVisitor.java:47)
	at com.intellij.psi.impl.source.tree.PsiErrorElementImpl.accept(PsiErrorElementImpl.java:42)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInjectedPsi(LocalInspectionsPass.java:823)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$inspectInjectedPsi$12(LocalInspectionsPass.java:388)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Haehnchen** [comment]
already fixed
