### ISSUE TITLE
Fatal error while wrapping text with `trans` block

### ISSUE THREAD

**Issue by mrix** [Haehnchen/idea-php-symfony2-plugin#918]
Hi. Thanks for this great tool.

These errors occur when I wrap some text with `trans` block in my Twig templates:
```
Worker exited due to exception: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.b(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
Argument for @NotNull parameter 'dataKey' of com/intellij/util/indexing/FileBasedIndexImpl.getValues must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'dataKey' of com/intellij/util/indexing/FileBasedIndexImpl.getValues must not be null
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationLookupElementsOnDomain(TranslationUtil.java:249)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getLookupElements(TranslationTagCompletionRegistrar.java:98)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.completion.CompletionContributor$1.addCompletions(CompletionContributor.java:41)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:121)
	at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:28)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.completion.XmlCompletionContributor$3.addCompletions(XmlCompletionContributor.java:139)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.XmlCompletionContributor.fillCompletionVariants(XmlCompletionContributor.java:194)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:831)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My environment:
* PhpStorm
  ```
  PhpStorm 2017.1.2
  Build #PS-171.4249.3, built on April 12, 2017
  JRE: 1.8.0_112-release-736-b16 amd64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  Linux 4.4.0-73-generic
  ```
* Symfony Plugin
  ```
  0.14.142
  ```

**Comment by skylord123** [comment]
Same issue as above. I was modifying a twig document using the twig function `constant` and adding backslashes to the class name when this occurred  (i.e. StoreBundle\Entity would be StoreBundle\\Entity). 

Error:

```
Worker exited due to exception: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Phpstorm (2017.1.3 vs 2017.1.2 as original post):
```
PhpStorm 2017.1.3
Build #PS-171.4424.11, built on April 26, 2017
Licensed to Anthony Tanner
Subscription is active until September 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-24-generic
```

Symfony Plugin `0.14.142`

**Comment by kitingChris** [comment]
Having the same issue with Phpstorm 2017.1.3 - Symfony Plugin 0.14.144 - Oracle JDK (build 1.8.0_111-b14) on Ubuntu 16.10
