### ISSUE TITLE
[Bug] Argument for @NotNull parameter 'key' MapReduceIndex.getData must not be null

### ISSUE THREAD

**Issue by kitingChris** [Haehnchen/idea-php-symfony2-plugin#931]
Since last update with Phpstorm 2017.1.3  - Symfony Plugin 0.14.144 I get the following exception:

```
Worker exited due to exception: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1061)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1067)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:927)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1102)
	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:48)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kitingChris** [comment]
Duplicate of #918
