### ISSUE TITLE
Null pointer exception in YamlHelper

### ISSUE THREAD

**Issue by alsii** [Haehnchen/idea-php-symfony2-plugin#942]
**PhpStorm** 2017.1.4
**Build** #PS-171.4694.2, built on May 16, 2017
**JRE:** 1.8.0_131-8u131-b11-1~bpo8+1-b11 i386
**JVM:** OpenJDK Server VM by Oracle Corporation
**Linux** 3.16.0-4-686-pae
**Symfony plugin** 0.14.145

**Exception data**
```
null
java.lang.NullPointerException
	at fr.adrienbrault.idea.symfony2plugin.util.yaml.YamlHelper.visitServiceCallArgument(YamlHelper.java:1032)
	at fr.adrienbrault.idea.symfony2plugin.util.yaml.YamlHelper.visitServiceCallArgumentMethodIndex(YamlHelper.java:1080)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getTypeHint(ServiceArgumentParameterHintsProvider.java:95)
	at fr.adrienbrault.idea.symfony2plugin.dic.ServiceArgumentParameterHintsProvider.getParameterHints(ServiceArgumentParameterHintsProvider.java:51)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:120)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.a(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Haehnchen** [comment]
fixed
