### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException

### ISSUE THREAD

**Issue by maxmedvedev** [Haehnchen/idea-php-symfony2-plugin#979]
Failed in PhpStorm 172.3317
```
Error while indexing /home/psakharov/adtech/php-atd/src/AtdBundle/Entity/FelixSegment.php
To reindex this file IDEA has to be restarted

com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:730)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:679)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:608)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:588)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:618)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:634)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getClassInterface(PhpElementsUtil.java:460)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getAnnotationRepositoryClass(EntityHelper.java:71)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getAnnotationRepositoryClass(DoctrineUtil.java:163)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.lambda$getClassRepositoryPair$0(DoctrineUtil.java:133)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitPhpDocTag(AnnotationElementWalkingVisitor.java:52)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitElement(AnnotationElementWalkingVisitor.java:32)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:32)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitElement(AnnotationElementWalkingVisitor.java:34)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:28)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:857)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getClassRepositoryPair(DoctrineUtil.java:118)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getClassRepositoryPair(DoctrineUtil.java:58)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.DoctrineMetadataFileStubIndex$MyStringStringFileContentDataIndexer.map(DoctrineMetadataFileStubIndex.java:47)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.DoctrineMetadataFileStubIndex$MyStringStringFileContentDataIndexer.map(DoctrineMetadataFileStubIndex.java:35)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$18(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1477)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.lambda$reindexRefreshedFiles$2(FileBasedIndexProjectHandler.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by donnerpeter** [comment]
Still an issue:

com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:81) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:787) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:745) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:725) VCS
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:519) VCS
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:374) VCS
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107) VCS
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95) VCS
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:785) VCS
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:765) VCS
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:819) VCS
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:838) VCS
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getClassInterface(PhpElementsUtil.java:380)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.EntityHelper.getAnnotationRepositoryClass(EntityHelper.java:71)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getAnnotationRepositoryClass(DoctrineUtil.java:168)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.lambda$getClassRepositoryPair$0(DoctrineUtil.java:133)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitPhpDocTag(AnnotationElementWalkingVisitor.java:51)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitElement(AnnotationElementWalkingVisitor.java:31)
	at com.jetbrains.php.lang.documentation.phpdoc.psi.impl.tags.PhpDocTagImpl.accept(PhpDocTagImpl.java:38) VCS
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70) VCS
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27) VCS
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65) VCS
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52) VCS
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79) VCS
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48) VCS
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.visitor.AnnotationElementWalkingVisitor.visitElement(AnnotationElementWalkingVisitor.java:33)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:27) VCS
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200) VCS
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733) VCS
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getClassRepositoryPair(DoctrineUtil.java:118)
	at fr.adrienbrault.idea.symfony2plugin.doctrine.DoctrineUtil.getClassRepositoryPair(DoctrineUtil.java:58)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.DoctrineMetadataFileStubIndex$MyStringStringFileContentDataIndexer.map(DoctrineMetadataFileStubIndex.java:47)
	at fr.adrienbrault.idea.symfony2plugin.stubs.indexes.DoctrineMetadataFileStubIndex$MyStringStringFileContentDataIndexer.map(DoctrineMetadataFileStubIndex.java:35)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309) VCS
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:113) VCS
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267) VCS
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1701) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1619) VCS
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:718) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1584) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1570) VCS

**Comment by andrey-sokolov** [comment]
Issue is still here and it should be fixed, cause the nested index invocation is against the design and can cause cycle re-index and race condition. Please refactor the code to postpone this evaluation to smart mode when indexing ends
