### ISSUE TITLE
Fatal error during project generation

### ISSUE THREAD

**Issue by iSDP** [Haehnchen/idea-php-symfony2-plugin#991]
**What happens**  
When trying to start a new Symfony project in IntelliJ it throws this error.

**Short Error**  
`java.lang.Object cannot be cast to fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerSettings`

**Stacktrace**
```
java.lang.Object cannot be cast to fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerSettings
java.lang.ClassCastException: java.lang.Object cannot be cast to fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerSettings
	at fr.adrienbrault.idea.symfony2plugin.installer.SymfonyInstallerProjectGenerator.generateProject(SymfonyInstallerProjectGenerator.java:25)
	at com.intellij.openapi.module.WebModuleBuilder.a(WebModuleBuilder.java:103)
	at com.intellij.openapi.module.WebModuleBuilder.commitModule(WebModuleBuilder.java:91)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:322)
	at com.intellij.ide.impl.NewProjectUtil.a(NewProjectUtil.java:149)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:71)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:231)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by lopatinas** [comment]
:+1: Same problem

**Comment by SandwichCZ** [comment]
Same problem, PhpStorm 2017.2.1

**Comment by martijnhartlief** [comment]
Same problem under 2017.2.1

**Comment by iSDP** [comment]
@Haehnchen it would be really great if you manage to fix this so we can start new Symfony projects from the IDE again.

**Comment by PandaDP** [comment]
Guys, put PHPStorm 2017.1.1 and everything will be OK. I had this problem with the symphony plugin in version 2017.2.1, I installed the version less and now it works

**Comment by iSDP** [comment]
@PandaDP I don't want to have to downgrade for a Plugin.

**Comment by jasonquick** [comment]
Also having this problem with identical error using 2017.2.1

**Comment by josefrvaldes** [comment]
Same here. Using last version of PHPStorm 2017.2.1 and windows 10.

**Comment by eldiablo62** [comment]
same problem with 2017.2.2

**Comment by Osch-info** [comment]
problem still resides with 2017.2.3

**Comment by SmR492** [comment]
same here. PHPStorm 2017.2.3

**Comment by ngkung** [comment]
same here. PHPStorm 2017.2.4

**Comment by Haehnchen** [comment]
fixed: plugin build against latest api

**Comment by Lehj14** [comment]
Hi, i just want to ask if this is already fixed? I am getting this error when trying to create a symfony project 2017.2
